### ISSUE TITLE
Table allows configuration of number column type

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#1011]
## 😯 Problem to Solve
A user needs to display numeric values to the user. These values may be integer or decimal based numbers.

The end user would like to be able to sort, filter, etc. based on these values. 
Note: This feature would not provide that direct functionality but is a consideration for this feature.

## 💁 Proposed Solution
The user should be able to provide simple, supported, configurations easily. 

## Open Questions
| Question                                                                      | Initial Recommendation     | Resolved | Decision |
|-------------------------------------------------------------------------------|----------------------------|----------|----------|
| Which formatting options do we need to provide?                               | Integer and Decimal        | No       |          |
| Should we provide config for prefix? (e.g. currency symbols)                  | No                         | No       |          |
| Should we provide config for prefix or suffix? (e.g. static string for units) | Yes                        | No       |          |
| How should we provide alignment?                                              | Always right-align content | No       |          |
| Which width modes should we support?                                | Both fixed pixel width and fractional width | No       |          |

## Other Considerations
Supporting the users local for number formatting
More info: [Intl.NumberFormat - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat#examples)

## References/Prior Art
[jQuery Grid Cells Formatting](https://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxgrid/jquery-grid-cellsformatting.htm)

```[tasklist]
## 📋 Tasks
- [ ] #887
- [ ] #1054
- [ ] #1224
- [x] Create base classes for text columns
- [x] Define API for numeric formatting
- [x] Define API for text alignment
- [x] Create custom elements for number column with basic API and default numeric formatting
- [x] Unit tests for formatting number edge cases (Inf, NaN, etc)
- [x] Add API to configure integer numeric formatting
- [x] Add API to configure decimal numeric formatting
- [ ] https://github.com/ni/nimble/issues/1293
- [x] Respect Nimble locale token for numeric formatting
- [x] Unit tests for invalid state with bad formatting configuration
- [x] Add API to configure text alignment
- [x] Angular integration
- [x] Blazor integration
```

**Comment by jattasNI** [comment]
I was curious about what kind of numeric formatting options we need. Here are the use cases I found in SLE that use either a number column type or a custom format function:
1. [data table grid](https://dev.azure.com/ni/DevCentral/_search?action=contents&text=dataType%3A%20%27number%27%20ext%3Ats%20path%3Aweb&type=code&lp=code-Project&filters=ProjectFilters%7BDevCentral%7DRepositoryFilters%7BSkyline%7D&pageSize=25&result=DefaultCollection/DevCentral/Skyline/GBmaster//Web/Workspaces/SystemLinkShared/projects/systemlink-lib-angular/data-table/src/components/sl-data-table-grid/sl-data-table-grid.component.ts) includes integer counts with default formatting
1. [executions grid](https://dev.azure.com/ni/DevCentral/_search?action=contents&text=formatFunction%20ext%3Ats%20path%3Aweb&type=code&lp=code-Project&filters=ProjectFilters%7BDevCentral%7DRepositoryFilters%7BSkyline%7D&pageSize=25&result=DefaultCollection/DevCentral/Skyline/GBmaster//Web/Workspaces/ExecutionManager/src/app/executions-grid/executions-grid.component.ts) converts a numeric enum to a user-visible string. I think we'd rather make this a dedicated enum column type
2. [test results grid](https://dev.azure.com/ni/DevCentral/_search?action=contents&text=formatFunction%20ext%3Ats%20path%3Aweb&type=code&lp=code-Project&filters=ProjectFilters%7BDevCentral%7DRepositoryFilters%7BSkyline%7D&pageSize=25&result=DefaultCollection/DevCentral/Skyline/GBmaster//Web/Workspaces/TestInsights/src/app/results/components/results-grid/results-grid.component.ts) formats elapsed time as "12 s" or "13 m, 12 s". I think we'd rather make this a dedicated elapsed time column type, possibly leveraging upcoming browser APIs like [temporal](https://tc39.es/proposal-temporal/docs/duration.html)
3. [files grid](https://dev.azure.com/ni/DevCentral/_search?action=contents&text=formatFunction%20ext%3Ats%20path%3Aweb&type=code&lp=code-Project&filters=ProjectFilters%7BDevCentral%7DRepositoryFilters%7BSkyline%7D&pageSize=25&result=DefaultCollection/DevCentral/Skyline/GBmaster//Web/Workspaces/AssetManagement/projects/asset-manager/src/app/components/files/sl-files-grid.component.ts) formats file sizes using units like bytes, KB, MB, etc. I think we'd make this a dedicated custom column type.
4. [wafer classification](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=%2FWeb%2FWorkspaces%2FWaferClassification%2Fsrc%2Fapp%2Frecipe-results%2Fcomponents%2Flots-table%2Flots-table.component.ts&_a=contents&version=GBmaster) has lots of numeric columns but I believe they're all integer counts

Other use cases include formatting dates, times, icons, arbitrary custom columns, etc are covered by other work items.

Initial conclusion: It might be possible to keep the number column type extremely simple to start with by using default numeric formatting and not allowing units. Posting this to capture notes and hear hot takes, but we can hash out in detail in an HLD.

**Comment by jattasNI** [comment]
The [SLS Tag grid](https://test.systemlink.io/#tagviewer) shows tag values with numeric formatting that is not end-user configurable. Some of these use cases also might require a custom column because tags can be various non-numeric data types.
 
![image](https://user-images.githubusercontent.com/10500124/215860734-4efc4fea-e2fe-4215-96ed-6e8f7261d4ce.png)
