### ISSUE TITLE
Table allows configuration of datetime column type

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#1014]
## 😯 Problem to Solve
There is a need to provide a date (and/or time) column type. Initially, only date may be needed.
Having a column for this type provides support for sorting, grouping and filtering. It will also be able to integrate locale specific formatting to support i18n and l10n.

### In
Displaying the date to the user in a locale correct format for numeric displays
Providing display format options (long year, short year, etc.)
Sorting of column works as expected

## Open Questions
- Do we need to support time display in the initial version?
  - Probably
- Do we provide numeric (01/01/2023) AND text (January 01, 2023) versions of formatting?
  - How does that work along with locale specific formatting?
- Will we need a 3rd party library for formatting? (date-fns, moment, luxon, etc.??). If so which one?
- What type(s) of input do we accept for this column type (Date object, timecode seconds, timecode ms.?)
- Which width modes should the column support? Both fixed pixel width and fractional width?

## Prior Art
- [x] #887

### Example of date being used
![image](https://user-images.githubusercontent.com/109235103/218489678-62dd6988-cfd3-4bb3-a28e-8555c8c2fe60.png)

![Image](https://user-images.githubusercontent.com/109235103/218791672-d00441d0-f99c-47d0-96ad-45b27033802a.png)

```[tasklist]
## 📋 Tasks
- [x] Create custom elements for date column with basic API and default date formatting
- [x] Unit tests for behavior with invalid dates
- [x] Unit tests for formatting number edge cases (Inf, NaN, etc)
- [x] Add API to configure custom date formatting
- [x] Unit tests for invalid state with bad formatting configuration
- [x] Respect Nimble locale token for date formatting
- [x] Angular integration
- [x] Blazor integration
```
