### ISSUE TITLE
nimble-anchor-menu-item component

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#1020]
## 😯 Problem to Solve
Like other components (tabs, buttons, tree-item), we need an anchor version of a `nimble-menu-item`

## 💁 Proposed Solution
It will look, visually, identical to a `nimble-menu-item` but will behave like an anchor/link.

- FAST component: 
- Visual Design: 

```[tasklist]
## 📋 Tasks
- [ ] nimble-anchor-menu-item spec
- [ ] nimble-anchor-menu-item custom element
- [ ] nimble-anchor-menu-item unit tests
- [ ] nimble-anchor-menu-item Storybook tests
- [ ] nimble-anchor-menu-item Storybook docs
- [ ] nimble-anchor-menu-item Angular wrapper
- [ ] nimble-anchor-menu-item Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
- [ ] Update Component Status table in README
```
