### ISSUE TITLE
Table keyboard interaction

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1137]
## 😯 Problem to Solve

We want users to be able to perform common table interactions via keyboard as well as via mouse. 

## 💁 Proposed Solution

- [Updated HLD](https://github.com/ni/nimble/blob/856f21dfc0630cc2267bd278b03a627c7e684dce/packages/nimble-components/src/table/specs/table-keyboard-navigation-hld.md)
- PR: #2172 

Earlier resources: #877 ; [interaction spec - currently has password error](https://xd.adobe.com/view/fa09e396-dbb9-40b8-547f-1cf9eab35a0b-8c38) (UXDesign1).

## 📋 Tasks
- [x] Demo prototype visuals to Brandon / get design feedback
- [x] Header/row/cell navigation via Up/Down/Left/RightArrow keys
- [x] Navigation within current row / header row with Tab/Shift-Tab
- [x] Return to navigation mode with Esc after action menu / cell contents are focused
- [x] Ensure keyboard navigation behaves sanely with mouse / other table interactions
- [x] Finalize impact to table / cell view APIs, if any
- [x] Get/address feedback on implementation via draft PR
- [x] Additional keys (Home/End/PgUp/PgDn/CtrlEnter/F2/etc)
- [x] Additional work identified in HLD

**Comment by atmgrifter00** [comment]
As part of the work in [this PR](https://github.com/ni/nimble/pull/1679), we are hiding the expand-collapse button for both group rows and parent rows from the accessibility tree. For parent rows this is meant to be a temporary state until we provide keyboard interactions for the table, at which point the expand-collapse button for parent rows should be focusable (but _not_ for group rows).

It's also worth noting that by hiding the expand-collapse button the accessibility score actually drops, seemingly because it expects the wrapped `button` element to have its `tabindex` set to `-1`, the same as the FAST component, but `tabindex` is [not passed through](https://github.com/microsoft/fast/blob/fd65254531ac3a593b32528d81b44ebf82c8e4ab/packages/web-components/fast-foundation/src/button/button.template.ts#L13) in the template (while `aria-hidden` is).

**Comment by m-akinc** [comment]
[HLD is in PR](https://github.com/ni/nimble/pull/1506), but needs some attention to keep moving forward.
