### ISSUE TITLE
Update storybook when SB7 regressions are fixed

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1146]
## 🧹 Tech Debt

As part of #1134 we filed some issues to Storybook about workarounds we had to adopt and features we had to disable. This issue tracks the work to adopt the fixes once they're available.

- [x] https://github.com/storybookjs/storybook/issues/21820. When this is fixed we can remove `patches/@storybook+html+7.0.0-rc.8.patch` and delete the peer dependency on `@storybook/html: *` from the root `package.json`. This is fixed in 7.0.8 but we can't uptake until this is fixed: https://github.com/storybookjs/storybook/issues/22384
- [x] Remove workaround in `storybook-declarations.d.ts` added in #1154 once this issue is fixed: https://github.com/storybookjs/storybook/issues/21887
- [x] Some code previews (table, tooltip, dialog) are not available in the Docs page. https://github.com/storybookjs/storybook/issues/21893
- [x] The `configureActions` parameter `depth` in `preview.js` changed meaning. We adapted in #1154 but if they change it back we should revert that. https://github.com/storybookjs/storybook/issues/21933
- [x] When we try to uptake the official release instead of an RC, nimble-table rows don't render. Root cause not yet identified, but this Nimble PR shows the issue. #1147
