### ISSUE TITLE
Document Figma component library in Storybook and nimble.ni.dev

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1263]
## 😯 Problem to Solve

We are far enough along transitioning components from XD to Figma that we should start promoting the Figma spec. Clients who want to build applications and Nimble devs who want to refer to it as the source of truth should have easy access to the library.

[Nimble_Components Figma spec link](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=0%3A1&t=GwhyllhJOJfOk5hc-1)

## 📋 Tasks

- [ ] Document what the usecases for Figma are
- [ ] Document process for getting access
- [x] Ensure the document is linked from nimble.ni.dev
- [x] Update component status table to link to Figma
- [ ] Consider linking to each component from Storybook
- [ ] Search .md docs in the repo for Adobe XD and update references
