### ISSUE TITLE
nimble-rich-text-editor and nimble-rich-text-viewer Components

### ISSUE THREAD

**Issue by vivinkrishna-ni** [ni/nimble#1288]
## 😯 Problem to Solve

Similar issues: #793 #794 
Requirement for `Comments`  Feature to create, view, and edit rich text content.
[UI Mockup For Comment](https://www.figma.com/file/Q5SU1OwrnD08keon3zObRX/SystemLink?type=design&node-id=6280-94045)

## 💁 Proposed Solution

- FAST component: N/A
- Other reference components: N/A

1. `nimble-rich-text-editor` to create and edit the rich text and get the `markdown` output.
2. `nimble-rich-text-viewer` to view the rich text.

## 📋 Tasks

- [ ] `nimble-rich-text-editor` and `nimble-rich-text-viewer` spec
- [ ] `nimble-rich-text-editor` and `nimble-rich-text-viewer` custom element
- [ ] `nimble-rich-text-editor` and `nimble-rich-text-viewer` unit tests
- [ ] `nimble-rich-text-editor` and `nimble-rich-text-viewer` Storybook tests
- [ ] `nimble-rich-text-editor` and `nimble-rich-text-viewer` Storybook docs
- [ ] `nimble-rich-text-editor` and `nimble-rich-text-viewer` Angular wrapper
- [ ] Add to Angular example app
- [ ] Update Component Status table in README

**Comment by m-akinc** [comment]
These components now exist in an "incubating" state. This issue now tracks any work necessary to bring it out of incubating.

**Comment by jattasNI** [comment]
We discussed the long term plan to move this out of incubating as part of #2406. The proposal there is that this component belongs in the Spright package within the Nimble repo. It's not a reflection of the quality, completeness, or usefulness of the component, just that it is more special-purpose than typical Nimble components like text field and table.

The work involved would be to move the code from packages/nimble* to packages/spright* and move the stories to the Spright section of storybook. This would be a breaking change for clients as they would now import from spright-angular, SprightBlazor, or spright-components packages. We'd need to either update client apps or notify them to make the updates themselves.

@vivinkrishna-ni What do you think of this proposal? If you like the direction, any chance your team would be interested in implementing that migration?

**Comment by vivinkrishna-ni** [comment]
@jattasNI We have discussed this internally within the team and there are a couple of questions we would like to clarify ourselves before taking up the work of migration for rich text components to Spright. I agree that certain criteria mentioned in the description of this issue have to be met to move it out of incubating. 

However, the rich text components might be general-purpose components (Maybe not the viewer, I don't have a strong opinion) that can belong to the core Nimble Design System. So it would be really helpful for us to understand why the components are a special-purpose than typical components in Nimble.

Also, will there be any chance that the components in Spright will be promoted (or is it not applicable?) to Nimble if all the optional requirements for Spright are met as mentioned in the [CONTRIBUTING.md](https://github.com/ni/nimble/blob/main/packages/spright-components/CONTRIBUTING.md)?

On the other hand, these components have been in incubation for a long time, as mentioned in #2406, and we agree that these can be moved to Spright as a solution for the issue. I will likely create a work item and link it to our backlog. However, we may not have the bandwidth to prioritize it for this cycle, but I believe we can take it up in the next cycle by considering based on the priorities.
