### ISSUE TITLE
Select and Combobox Refresh

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#1303]
## 📌 User Story

The following are topics that should be addressed (included or closed):

Both: 
- [x] Placeholder option (when a user has not selected a value): https://github.com/ni/nimble/issues/350
- [ ] Placeholder for empty options list (when filter on combobox or select results in all options being removed): https://github.com/ni/nimble/issues/1309
- [ ] Labels: https://github.com/ni/nimble/issues/94 https://github.com/ni/nimble/issues/280
- [x] Limit the height of the dropdown: https://github.com/ni/nimble/issues/1870
- [x] Clear selected value: https://github.com/ni/nimble/issues/1951
- [ ] Dynamically fetched options (show a spinner while fetching options): 
    - https://github.com/ni/nimble/issues/1311
    - https://github.com/ni/nimble/issues/506#issuecomment-1611766299
    - https://github.com/ni/nimble/issues/1866
- [x] Groupable options: https://github.com/ni/nimble/issues/791
- [ ] ~~"Load more" / "Show all" / Action button / Checkbox (use case: dynamic loading of additional options)~~
- [ ] ~~More filter options~~
    - ~~Case sensitive~~
- [ ] Slottable content in options (i.e. icons): https://github.com/ni/nimble/issues/1135 https://github.com/ni/nimble/issues/1254
- [ ] ~~Slottable content in selector area: https://github.com/ni/nimble/issues/1310~~
- [ ] ~~Editable options (add new entries): https://github.com/ni/nimble/issues/507~~
- [ ] ~~Context menu key interactions: https://github.com/ni/nimble/issues/798~~
- [ ] ~~Virtualization of options: https://github.com/ni/nimble/issues/710~~
- [ ] ~~Visual when used in table: https://github.com/ni/nimble/issues/1190~~

Select: 
- [x] Filterable: https://github.com/ni/nimble/issues/1273
- [ ] ~~Multiselect: https://github.com/ni/nimble/issues/341~~ will implement as a picker component

Combobox:
- [ ] ~~Autocomplete mode that allows searching any part of the string: https://github.com/ni/nimble/issues/535~~
- [ ] Control Value Accessor behavior: https://github.com/ni/nimble/issues/682 https://github.com/ni/nimble/issues/1168
- [x] Dynamic options + good filtering modes allow us to make the open api private again, discussion for why it was made public: https://github.com/ni/nimble/issues/1324#issuecomment-1631540180
- [ ] ~~Stop altering `hidden` state of options: https://github.com/ni/nimble/issues/1902~~

**Comment by jattasNI** [comment]
First priorities in cycle 3:
1. #791
2. #1273

**Comment by jattasNI** [comment]
## Interaction design requests

1. Fill out IxD spec for select / combobox with particular focus on usage guidance (and considering the roadmap laid out in the linked issues above)

**Comment by SPathani-NI** [comment]
Currently due to lack of label on select component it is looking out of place when used alongside other components.
Also, it is not responding correctly to "width" CSS property current workaround is using "min-width".

**Comment by atmgrifter00** [comment]
@leslieab, I've added a new bullet item to the description for tracking a decision on whether we should offer a means for a client to configure the height of the dropdown. We've now seen a couple of requests for this, but aren't currently tracking that particular aspect in a dedicated issue.

**Comment by rajsite** [comment]
Unofficial motto for this issue:
![image](https://github.com/ni/nimble/assets/1588923/f2c9e8a6-367b-421e-ba3e-4e347cf9c900)
