### ISSUE TITLE
nimble-accordion Visual Design Request / Tracking

### ISSUE THREAD

**Issue by aidendk** [ni/nimble#1399]
## 📌 Request Background

There are several open questions with the current visual design. They're tracked here for background but won't block initial approval of this component spec.

[Figma nimble-accordion UX designs](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?node-id=1359%3A31784&mode=dev). 

## 🎯 Core Requirements

1. The Figma spec has designs for two accordion item heights, 24px and 32px. The 32px will be implemented first as this matches other components. We can implement the 24px variation when we receive client requests for it.

2. The Figma spec only shows designs for one accordion item at a time. How should accordion items in each appearance type be separated from each other (ex. a line between accordion items, transparent space between accordion items, etc.)? Because there's only one accordion item design at a time, it is also unclear if error-visible is a nimble-accordion-item specific state, or if it should affect all accordion items and be used in the nimble-accordion component.

3. The Figma spec does not have a design for the "error" `focusVisible` state. This might be confusing, as keyboard users who tab to the error accordion will suddenly see the red border and exclamation mark icon disappear in the `focusVisible` state.

4. When should each `appearance` type be used? Will there be specific guidance on this, and if so, will it be similar to the guidance for other Nimble components that use the same `appearance` types (ex. the Nimble-Button)?

## 🍆 Non-requirements

N/A

## 🥅 Acceptance Criteria

- [ ] Visual Design Spec submitted (link)
- [ ] Visual Design Spec reviewed by design team
- [ ] Visual Design Spec reviewed by dev team
