### ISSUE TITLE
Add a badge component

### ISSUE THREAD

**Issue by pakdev** [ni/nimble#1428]
## 😯 Problem to Solve

A recent project required a badge component to indicate the number of notifications someone has e.g.

![image](https://github.com/ni/nimble/assets/1248927/4392ce98-b7e1-458d-9e69-b044509ea6d2)

## 💁 Proposed Solution

Create a badge component similar to [Angular Material's](https://material.angular.io/components/badge/overview)

## 📋 Tasks

- [ ] nimble-{name} interaction design issue
- [ ] nimble-{name} interaction design spec
- [ ] nimble-{name} visual design issue
- [ ] nimble-{name} visual design spec
- [ ] nimble-{name} spec
- [ ] nimble-{name} custom element
- [ ] nimble-{name} unit tests
- [ ] nimble-{name} Storybook tests
- [ ] nimble-{name} Storybook docs
- [ ] nimble-{name} Angular wrapper
- [ ] nimble-{name} Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
- [ ] Update Component Status table in README and incubating status

**Comment by jattasNI** [comment]
Thanks for filing @pakdev! Some questions for you to help us understand scope and priority:
1. do you only need the badge on tabs or are you aware of use cases to add a badge on other components (e.g. buttons, text)? Do you need the Material feature that lets you position it in arbitrary locations?
2. any other requirements for the content of the badge? For example:
    1. Is it always a single digit number? 
    2. Different background colors for different types of notification? 
    3. Any additional content to display on hover?
3. does this request have a deadline?

**Comment by pakdev** [comment]
1. Today, I need the badge on buttons (my example above uses my own tab control whose tabs are `mat-icon-button`'s containing `mat-icon`'s). I do not currently need arbitrary locations (top-right is sufficient)
2. The badge content must allow for multi-digit numbers. It would be nice if different background colors were supported, though I am not currently using that feature. I'm not sure I'd ever react to hover events.
3. No deadline as I have workarounds

**Comment by jattasNI** [comment]
@fredvisser let's discuss this at an upcoming grooming meeting. Some questions to drive:
2. any changes to our intake process? (component status table? tags to track issues moving from initial request to prioritized?)
3. any outreach to gather additional requirements from other clients?
4. what's the priority for IxD / VxD / dev? Any work items to create?

**Comment by kroeschl** [comment]
Seconding this request for RDSS MTO's internal Dashboard product.

**Comment by NIbokeefe** [comment]
Will something like this work for you @pakdev @kroeschl?

<img width="608" alt="Screen Shot 2023-09-13 at 4 17 11 PM" src="https://github.com/ni/nimble/assets/106594349/be6e5803-fffa-48be-a862-cbead58de209">


Early on in my button spec I had a design in place for badges but we did not have a use case at the time, so it was pulled.  We did however implement notification alerts in multiple colors for tabs in SLE.  It's a similar layout but instead a circular dot with no type.

@jattasNI

**Comment by kroeschl** [comment]
@NIbokeefe Our use case is text with a badge, so something like this:
![image](https://github.com/ni/nimble/assets/60117794/983e753d-29a5-4011-a7e3-2a91de4236f3)

The styling you showed looks fine as long as it can apply to more than just buttons.

**Comment by pakdev** [comment]
> Will something like this work for you @pakdev @kroeschl?

Can the badge only appear on the left side?

**Comment by kroeschl** [comment]
Not in our case, though I'm not wondering if we're just abusing the badge concept and should re-think the UI. We have a table and decorate the name column text with a count of related active resources:
![image](https://github.com/ni/nimble/assets/60117794/42e7b626-a2bc-4d7d-9f7c-8dc5716d64a8)

**Comment by NIbokeefe** [comment]
@TJ-G 

Here's the task for the badge feature I mentioned during our UX Consulting meeting today.

**Comment by NIbokeefe** [comment]
@pakdev @kroeschl @jattasNI @fredvisser 

Do you all still need this badge concept?  This task has been open for a while, so has any priorities changed and do you have a placeholder solution currently implemented to this problem?

**Comment by kroeschl** [comment]
We'd still like it. No priorities have changed, and we're currently using Angular Material's [Badge](https://material.angular.io/components/badge) component:
![image](https://github.com/user-attachments/assets/8fbc53ec-4584-42bc-ab6b-605bcc66f700)

**Comment by pakdev** [comment]
The project I needed this component for was a PoC; whether I need it in the future or not is TBD. I opened this issue because 1. I _wanted_ it at the time and had to create a workaround 2. it seems like a pretty ubiquitous component since it exists in Angular Material
