### ISSUE TITLE
nimble-split-button Component

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1523]
## 😯 Problem to Solve

A button with a menu button immediately next to it is a common pattern which Nimble doesn't currently support
![image](https://github.com/ni/nimble/assets/10500124/2158ce8d-7bd4-410c-9d5d-d2b912feebff)

This [came up](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/539602#1694547139) in the SLE Feeds app. We can propose simple workarounds for now (e.g. a button and a menu button separated by some padding)

It has a similar name to #298 but I believe they are different.

## 💁 Proposed Solution

- FAST component: 
- Other reference components: 

## 📋 Tasks

- [ ] nimble-{name} interaction design issue
- [ ] nimble-{name} interaction design spec
- [ ] nimble-{name} visual design issue
- [ ] nimble-{name} visual design spec
- [ ] nimble-{name} spec
- [ ] nimble-{name} custom element
- [ ] nimble-{name} unit tests
- [ ] nimble-{name} Storybook tests
- [ ] nimble-{name} Storybook docs
- [ ] nimble-{name} Angular wrapper
- [ ] nimble-{name} Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
- [ ] Update Component Status table in README and incubating status

**Comment by sudharsan-ni** [comment]
@jattasNI I think our squad might need split button for one of our upcoming workflows. I saw that Feeds workflow has a need for this component as well. Are you planning to prioritize this component? If yes, by when will this component be available?

P.S. I recently took up PO responsibilities for LIMS. So, I am a bit new to this process. How do POs provide inputs to Design System squad on requirements?

**Comment by jattasNI** [comment]
@sudharsan-ni thanks for commenting! That's one good way to express inputs on priorities and requirements. For bigger components or more in depth discussions you can also come to the UI working group meeting or meet with me and/or @fredvisser directly.

We haven't nailed down our 2024 Cycle 1 plan yet but it's not likely this will fit. Your options would include:
1. using the workaround described in the issue description (separate button and menu button)
2. getting your team to contribute the component. If you want to go that direction we should meet with the devs and manager to talk about the steps involved.

**Comment by jattasNI** [comment]
@kroeschl if you're building an Angular app that can use our internal library [`@ni-kismet/systemlink-lib-angular`](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=/Web/Workspaces/SystemLinkShared/projects/systemlink-lib-angular&_a=contents&version=GBmaster&anchor=systemlink-lib-angular) then you could consider using [its split button](https://stratus-storybook.ni.dev/?path=/story/components-split-button--with-values) which is composed from Nimble components ([source](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=/Web/Workspaces/SystemLinkShared/projects/systemlink-lib-angular/src/sl-split-button&_a=contents&version=GBmaster)).

Since SystemLink has been satisfied with that component it's unlikely we'll prioritize adding it to Nimble in the near future. We'd welcome a contribution if your team has bandwidth: feel free to reach out.

If neither of those are options you could consider forking the SystemLink implementation into your app: not the best option for shared code but at least it will be consistent (at least until one of the implementations changes).

FYI @fredvisser

**Comment by kroeschl** [comment]
@jattasNI I'd also be open to contributing if there was a finalized design from the UX folks.

**Comment by rajsite** [comment]
> I'm looking for just a split button without a dropdown menu (so just two buttons grouped together)--I can file a new request separate from this. My hacked-up solution looks like this for now:

@kroeschl @jattasNI This sounds like the toggle button group component: https://github.com/ni/nimble/issues/298
