### ISSUE TITLE
Elapsed time table column

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#1569]
## 😯 Problem to Solve

SLE apps need a column that displays elapsed time.

See AzDO feature: https://ni.visualstudio.com/DevCentral/_workitems/edit/2526116

## 📋 Tasks

- [x] [nimble-duration-text-column spec](https://github.com/ni/nimble/blob/main/packages/nimble-components/src/table/specs/table-column-specs/table-column-duration-text-hld.md)
- [x] nimble-duration-text-column custom element
- [x] nimble-duration-text-column unit tests
- [x] nimble-duration-text-column Storybook tests
- [x] nimble-duration-text-column Storybook docs
- [x] nimble-duration-text-column Angular wrapper
- [x] nimble-duration-text-column Blazor wrapper
- [x] Add to Angular example app
- [x] Add to Blazor example app

**Comment by msmithNI** [comment]
#1619 added Blazor/Angular integration, and added the duration column to the all-components bundle.
