### ISSUE TITLE
Number-text table column unit support

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#1573]
## 😯 Problem to Solve

SLE needs a table column to display file sizes.
See AzDO Feature: https://ni.visualstudio.com/DevCentral/_workitems/edit/2526114

## 📋 Tasks

- [x] spec
- [ ] element updates, tests, and docs
- [ ] update Angular wrapper, tests
- [ ] update Blazor wrapper, tests
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
