### ISSUE TITLE
Error state for nimble-checkbox

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1852]
## 😯 Problem to Solve

Nimble components that can be used as `inputs` within forms or property-editors should support an error state. The `nimble-checkbox` doesn't currently have an error state. 

## 💁 Proposed Solution

Add `error-visible` and `error-text` properties to the `nimble-checkbox`.

![image](https://github.com/ni/nimble/assets/1458528/c1e43ff0-eff2-4f1a-8b3b-dc05bc104fc3)

Use the [Figma design](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1295-63148&mode=dev) for alignment and spacing.
![Screenshot 2024-02-21 at 2 55 18 PM](https://github.com/ni/nimble/assets/1458528/52c5dff7-9a6e-44a7-a73a-19cb3c7feba0)

## 📋 Tasks
- [ ] update nimble-checkbox custom element
- [ ] update nimble-checkbox unit tests
- [ ] update nimble-checkbox Storybook tests
- [ ] update nimble-checkbox Storybook docs
- [ ] update nimble-checkbox Angular wrapper
- [ ] update nimble-checkbox Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
