### ISSUE TITLE
Error state for nimble-radio-group

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1853]
## 😯 Problem to Solve

Nimble components that can be used as `inputs` within forms or property-editors should support an error state. The `nimble-radio-group` doesn't currently have an error state. 

## 💁 Proposed Solution

Add `error-visible` and `error-text` properties to the `nimble-radio-group`.

![image](https://github.com/ni/nimble/assets/1458528/c1e43ff0-eff2-4f1a-8b3b-dc05bc104fc3)

Use the [Figma design](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1295-63148&mode=dev) for alignment and spacing.
![image](https://github.com/ni/nimble/assets/1458528/b91505d2-5111-46f9-b15d-008a4b5e41c3)

## 📋 Tasks
- [ ] update nimble-radio-group custom element
- [ ] update nimble-radio-group unit tests
- [ ] update nimble-radio-group Storybook tests
- [ ] update nimble-radio-group Storybook docs
- [ ] update nimble-radio-group Angular wrapper
- [ ] update nimble-radio-group Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
