### ISSUE TITLE
Error state for nimble-switch

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1854]
## 😯 Problem to Solve

Nimble components that can be used as `inputs` within forms or property-editors should support an error state. The `nimble-switch` doesn't currently have an error state. 

## 💁 Proposed Solution

Add `error-visible` and `error-text` properties to the `nimble-switch`.

![image](https://github.com/ni/nimble/assets/1458528/c1e43ff0-eff2-4f1a-8b3b-dc05bc104fc3)

Use the [Figma design](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1671-73469&mode=dev) for alignment and spacing.

![Screenshot 2024-02-21 at 3 06 11 PM](https://github.com/ni/nimble/assets/1458528/e57cd258-132c-4909-82c4-ad83f7ced40b)

## 📋 Tasks
- [ ] update nimble-switch custom element
- [ ] update nimble-switch unit tests
- [ ] update nimble-switch Storybook tests
- [ ] update nimble-switch Storybook docs
- [ ] update nimble-switch Angular wrapper
- [ ] update nimble-switch Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
