### ISSUE TITLE
Bring number-column formatting options to nimble-number-field 

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1855]
## 😯 Problem to Solve

Clients like DFF require locale-specific, decimal number formatting in the `nimble-number-field`.

## 💁 Proposed Solution

Adopt the decimal formatting options from the `nimble-table-column-number-text` component.
- Support for the `format` property including the `default` and `decimal` options
- Support for the `decimal-digits` and `decimal-maximum-digits` properties

Adopt the automatically locale specific number formatting from the `nimble-table-column-number-text` component.
- E.g. Should render `1,002.9` as `1.002,9` for German locales.

## 📋 Tasks
- [ ] update nimble-number-field custom element
- [ ] update nimble-number-field unit tests
- [ ] update nimble-number-field Storybook tests
- [ ] update nimble-number-field Storybook docs
- [ ] update nimble-number-field Angular wrapper
- [ ] update nimble-number-field Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app

**Comment by rajsite** [comment]
@fredvisser is this for number inputs or number rendering as text? Number input support is likely to be challenging.

**Comment by jattasNI** [comment]
Some of the challenges if we want to support formatting inputs:

1. localization. Right now we always use `.` for decimal separator and `,` for thousands separator, but some locales use the opposite or other characters like space. If the user types one of those characters, how do we interpret it? If we decide to allow inputting only in en-us, will it be weird to switch the format to a different locale after the user commits the value?
2. if a number is being formatted with a limited number of digits but the user inputs a higher precision number, what happens to the extra digits? Are they discarded completely? Or are they persisted in the value but truncated from the display?

**Comment by ChrisDecombe** [comment]
Answer to point 1: The input format should be depending on the language set on the UI (Browser). YOu should save always in the same format independent to the display format.

Answer to point 2: If the field is configured with 2 digits after the comma. If you try to enter a third digit this digit should not be displayed in the input field and it shouldn't be saved.

**Comment by rajsite** [comment]
Ran into the maskito library which looks potentially promising for building up some forms of formatted text input: https://maskito.dev/getting-started/what-is-maskito

**Comment by jattasNI** [comment]
Very tentative proposal outline after 15 minutes of chatting with @fredvisser. Feedback welcome.
1. fork FAST template and base class, rip out their validation of allowed characters/min/max
2. integrate the maskito library linked above
    - it does live validation/formatting as the user types (requires you to give it access to the underlying HTML input)
    - it looks like it can be configured for the use cases we care about: localized input and display, restricting number of digits
    - it's not locale aware itself but we could generate a maskito config based on the Nimble-detected locale
    - later we may be able to use it for date inputs too
3. open UX questions: are there any maskito behaviors we're not happy with? 
    - does it allow programmatically displaying an invalid value (in order for us to show an error while preserving that value)
    - do we like its behavior of being permissive with pasted content but restrictive with typed content?
5. open API design / implementation questions
   - does maskito support the same formatting options that we expose on number column? If yes, should we expose the same API? Or something less configurable?
   - what behaviors do we want / get from maskito around form validation (both native and framework-specific)?

**Comment by rajsite** [comment]
Continuing brainstorming. Maybe the `numeric-text-field` API surface goal is that of `input[type="number"]` + appearance properties with the intention of being swappable and more generic (a thin wrapper over `input[type="number"]`).

Other input formats would be separate controls. If you have a simple numeric input you don't need to pay the tax of importing the maskito library (especially the [phone number input](https://maskito.dev/addons/phone) which has a [500kb dependency](https://www.npmjs.com/package/libphonenumber-js) 🤪).

**Comment by jattasNI** [comment]
Checking for understanding: with your first proposal we would end up with something like this (names TBD)
1. `numeric-text-field` - basically what we have today, includes styling and `min`/`max` but no localization or formatting. Lean and compatible with `input[type=number]` but less powerful than the options below
2. `formatted-numeric-text-field` - basically what I proposed in my comment, a text field with powerful numeric formatting options provided by maskito
3. `phone-number-text-field`, `date-text-field`, `time-text-field`, etc following the same architecture as 2 but preconfigured with other maskito plugins

While in your second proposal the customization would be provided by the plugin child element. In that approach the parent might not even need to be "numeric", it could just be `nimble-input` or `nimble-configurable-text-field` and the child could provide all the configuration.

**Comment by rajsite** [comment]
Sounds right. For the plugin approach maybe we would keep separate elements based on types on the api surface.

`<numeric-text-field><formatter-date></></>` // unix timestamp numbers
`<text-field><formatter-date></></>` // iso string dates
`<text-field><formatter-phone-number></></>` // phone number string
`<numeric-text-field><formatter-integer></></>` // doubles, but always the integer subset
`<numeric-text-field><formatter-double></></>` // doubles
`<numeric-text-field><formatter-zip-code></></>` // doubles, but always the integer subset
`<big-int-text-field>`

Think complexity on the plugin approach is designing the API surface and plugin points (something like providing a custom element that implements the masked text, provide function / operation for increment, decrement, getting current value, setting validity config like min, max, and reporting validity state)

**Comment by jattasNI** [comment]
I thought of another possible short term direction: to put this in a new Spright component. Some rationale:

1. the formatting options are currently only needed by one client: DFF
2. the localization would be useful to everyone but I think most SLE number fields currently show integers so there isn't any format difference, meaning this feature is also only really needed for DFF
3. we're trying out a new library in maskito
4. we're trying out new UX patterns in how maskito behaves
5. the API design seems possibly expensive to get right, especially if we want it to be pluggable

This would likely be contributed by a client team so would require a lot of guidance from Nimble maintainers to solve all of these in a generic forward looking way. Putting it in spright lets us treat some of these decisions as more of an experiment.

**Comment by rajsite** [comment]
Remembered integer input being annoying with `input[type="number"]` and found the [article on it](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/). Recommendation there is `<input type="text" inputmode="numeric" pattern="[0-9]*">`. Looks like in nimble-text-field we are forwarding `pattern` but we need to add and forward `inputmode` as well. They even updated the HTML spec to recommend this approach for the integer use case (zip code, credit card, etc): https://html.spec.whatwg.org/multipage/input.html#when-number-is-not-appropriate

**Comment by jattasNI** [comment]
I spent a couple hours hacking up a prototype of a Maskito-based spright number input this afternoon. You can see the changes in [the branch spright-formatted-numeric-maskito](https://github.com/ni/nimble/compare/spright-formatted-numeric-maskito) and you can see a [demo in storybook](https://60e89457a987cf003efc0a5b-hvatjipwqu.chromatic.com/?path=/docs/spright-formatted-number-field--docs).

The current state of affairs is that I hardcoded a Maskito configuration to only allow German input with 2 decimal digits (copied from their [separators example](https://maskito.dev/kit/number#separators). It has styling from the nimble-number-field but I had to rip out a whole bunch of its functionality.

The big question if we create a new Spright component is how much of the number field API do we want to continue to support, and then what is the right amount of implementation to share (possibly none). Here are some of the things [I ripped out](https://github.com/ni/nimble/commit/c1d19ef012a0d9defea9e90631aaed3e07e43099) in making this work. I think we'll want to bring most of it back, but right now the numeric implementation lives in FAST and is tied up with all of the input handling code we want to delete, so it's not trivially sharable.
1. value property (obviously we'll need that)
2. stepper buttons and step attribute
3. min and max
4. required-visible
5. disabled 
6. readonly
7. minlength and maxlength
8. most of the ARIA
