### ISSUE TITLE
nimble-toggle-tip Component

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1876]
## 😯 Problem to Solve

Complex forms and editor views built with nimble input components require field specific context help. While we've previously considered creating a [nimble-tooltip](https://github.com/ni/nimble/issues/309) to show contextual information, a _nimble-toggle-tip_ has several benefits over the tooltip.

_Persistence_: A toggle-tip stays visible until the user decides to close it. This allows the user to interact with the information, such as copying text or clicking links. Tooltips, on the other hand, typically disappear when the user moves the cursor.

_Keyboard accessibility_: The user can use the keyboard to focus on the toggle-tip icon and open or close the toggle-tip with only the keyboard.

_Complex Information_: Toggle-tips can be better for displaying more complex information, including images, links, or formatted text. Tooltips are usually limited to simple, short text.

_Mobile Friendliness_: Toggle-tips can be more mobile-friendly as they can be triggered by taps and remain visible. Tooltips often rely on hover interactions, which don't translate well to touch interfaces.

## 💁 Proposed Solution

![image](https://github.com/ni/nimble/assets/1458528/4efd992c-258b-423b-ba3e-243fd2aac310)

The toggle-tip will be predominately added to control labels. 

Consider:
- Should we add a 'no outline' appearance mode for the icon button and use that here?
- Add a slot to the label or all controls?

- References:
  - https://inclusive-components.design/tooltips-toggletips/
  - https://accessibility.pearson.com/resources/developers-corner/reference-library/tooltips-and-toggletips/index.php

- Other reference components: 
  - https://grafana.com/developers/saga/Components/toggletip
  - https://carbondesignsystem.com/components/toggletip/usage/

## 📋 Tasks

- [ ] nimble-toggle-tip interaction design issue
- [ ] nimble-toggle-tip interaction design spec
- [x] nimble-toggle-tip [visual design issue](https://github.com/ni/nimble/issues/1690)
- [x] nimble-toggle-tip [visual design spec](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=5308-156796&mode=dev)
- [ ] nimble-toggle-tip spec
- [ ] nimble-toggle-tip custom element
- [ ] nimble-toggle-tip unit tests
- [ ] nimble-toggle-tip Storybook tests
- [ ] nimble-toggle-tip Storybook docs
- [ ] nimble-toggle-tip Angular wrapper
- [ ] nimble-toggle-tip Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
- [ ] Update Component Status table in README and incubating status

**Comment by jattasNI** [comment]
The RDSS team working on the SLE Config Utility app mentioned they'll be interested in this component. They're currently building it themselves with a button and tooltip.

![image](https://github.com/ni/nimble/assets/10500124/171eeabd-4f55-4d58-b2e7-ae5f2c0681e8)

**Comment by jattasNI** [comment]
We should consider re-enabling the tooltip matrix tests when we work on this feature. #1106

**Comment by jattasNI** [comment]
The SLE schedule view [introduced a toggle-tip-like component in this PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/787939). It uses the info icon but only shows more info on hover, not click. When this component is available we should look at replacing that (and see if there are other SLE apps that have adopted similar patterns, possibly by searching source for that icon).

![image](https://github.com/user-attachments/assets/007d4fb2-fb5b-404f-affa-55619bbdc9a6)
