### ISSUE TITLE
Error state for nimble-checkbox

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#2018]
# 💡 Updated Component

## 😯 Problem to Solve

We need to finish out our first-class form support for our core input components by supporting error states and text for all components commonly used in forms.

## 💁 Proposed Solution

Leverage the existing patterns/APIs to configure error state on `nimble-checkbox`

I.e. Add `error-visible` and `error-text` properties to the `nimble-checkbox`.

![image](https://github.com/ni/nimble/assets/1458528/7b9eaebf-b3bc-46ae-9ef1-06ac325e6d62)

## 📋 Tasks

- [ ] ~~nimble-checkbox interaction design issue~~
- [ ] ~~nimble-checkbox interaction design spec~~
- [x] nimble-checkbox [visual design issue](https://github.com/ni/nimble/issues/1765)
- [x] nimble-checkbox [visual design spec](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1295-63148&mode=design)
- [x] Update nimble-checkbox [spec](https://github.com/ni/nimble/blob/main/packages/nimble-components/src/checkbox/specs/error-state.md)
- [x] Update nimble-checkbox custom element
- [ ] Update nimble-checkbox unit tests
- [x] Update nimble-checkbox Storybook tests
- [x] Update nimble-checkbox Storybook docs
- [ ] Update nimble-checkbox Angular wrapper
- [ ] Update nimble-checkbox Blazor wrapper
- [ ] Update Angular example app
- [ ] Update Blazor example app
