### ISSUE TITLE
Error state for nimble-radio-group

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#2019]
# 💡 Updated Component

## 😯 Problem to Solve

We need to finish out our first-class form support for our core input components by supporting error states and text for all components commonly used in forms.

## 💁 Proposed Solution

Leverage the existing patterns/APIs to configure error state on `nimble-radio-group`

I.e. Add `error-visible` and `error-text` properties to the `nimble-radio-group`.

![Screenshot 2024-04-16 at 3 44 26 PM](https://github.com/ni/nimble/assets/1458528/92c5dbc1-2b27-40b4-8944-c2f61cfd3d46)

## 📋 Tasks

- [ ] ~~nimble-radio-group interaction design issue~~
- [ ] ~~nimble-radio-group interaction design spec~~
- [x] nimble-radio-group [visual design issue](https://github.com/ni/nimble/issues/1765)
- [x] nimble-radio-group [visual design spec](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1295-63148&mode=design)
- [ ] Update nimble-radio-group spec
- [ ] Update nimble-radio-group custom element
- [ ] Update nimble-radio-group unit tests
- [ ] Update nimble-radio-group Storybook tests
- [ ] Update nimble-radio-group Storybook docs
- [ ] Update nimble-radio-group Angular wrapper
- [ ] Update nimble-radio-group Blazor wrapper
- [ ] Update Angular example app
- [ ] Update Blazor example app
