### ISSUE TITLE
nimble-search-text Component

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#2021]
# 💡 New Component

## 😯 Problem to Solve

SLE often uses `nimble-table` along with a text field that allows users to filter the rows of data in the table (see #1923). Instead of using a nimble-text-field, we should create a `nimble-search-text` component, so that it has the correct semantics and search IxD.

## 💁 Proposed Solution

![Screenshot 2024-04-17 at 2 28 56 PM](https://github.com/ni/nimble/assets/1458528/4d4f8761-54b8-45f5-b9ef-b98d99d2a7cc)

- [FAST component](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/search/README.md)
- Other reference components: 
  - [Carbon](https://carbondesignsystem.com/components/search/usage/)
  - [Lightning](https://www.lightningdesignsystem.com/guidelines/search/in-context/#site-main-content)
  - [Cauldron](https://cauldron.dequelabs.com/components/SearchField)
  - [Vibe](https://style.monday.com/?path=/docs/inputs-search--docs)

## 📋 Tasks

- [ ] nimble-search-text interaction design issue
- [ ] nimble-search-text interaction design spec
- [ ] ~~nimble-search-text visual design issue~~
- [x] nimble-search-text [visual design spec](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1453-32903&mode=design)
- [ ] nimble-search-text spec
- [ ] nimble-search-text custom element
- [ ] nimble-search-text unit tests
- [ ] nimble-search-text Storybook tests
- [ ] nimble-search-text Storybook docs
- [ ] nimble-search-text Angular wrapper
- [ ] nimble-search-text Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
- [ ] Update Component Status table in README and incubating status

**Comment by jattasNI** [comment]
Open questions:
 - is this a new Nimble component or a configuration of the text field (which gets shared in an SLE shared library)?
 - the text field icon is currently black instead of grey despite not being interactable. Is this a bug?
 - is there a specific ARIA role for search that we should apply?
 - "search" vs "filter" as the default terminology

Fred is working on SLE pattern documentation that will answer some of these but not all
