### ISSUE TITLE
Wafer Map High Performance Redesign

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#2034]
# 🙋 Feature Request

## 😯 Problem to Solve

The Wafer Map has new rendering target goals for drawing a large number of wafers.

## 💁 Proposed Solution

See the [Rendering++](https://github.com/ni/nimble/blob/main/packages/nimble-components/src/wafer-map/specs/features/rendering.md) spec.

## 📋 Tasks

- [ ] Render Dies
   will have async await  for promises and error handling of rejection
- [ ] Refactor Model and state management
   will split state on responsibility and sync it between wafer and worker 
- [ ] Render text and colors (PR is drafted)
   will bring parity with the old renderer
- [ ] Remove legacy code
   will leave only the new update cycle inside the wafer map component
- [ ] Create error handlig
   will cover thread saturation and strict browser settings
- [ ] Sync rendering to animation frames
   will make updates smooth and will allow for rendering interuptions for large wafers
