### ISSUE TITLE
Required State for all input controls

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#2100]
# 🙋 Feature Request

## 😯 Problem to Solve

![image](https://github.com/user-attachments/assets/a6751718-f569-4463-8dcf-345a250e7510)

Input controls are often used in forms or property editor dialogs. Often the user is required to provide an input to the control before the form can be submitted or before the property changes can be saved.

With Nimble controls today, client applications will manually add … (Required) to the control's placeholder text or to the label.

We need to provide a standardized way for the application to let the end-user know that a control is required.

Input controls:
- Combobox
- Number Field
- Radio Group
- Select
- Text Area
- Text Field

Don't need to support:
- Checkbox
- Switch button

## 💁 Proposed Solution

https://www.w3schools.com/tags/att_input_required.asp

Per the [visual design](https://github.com/ni/nimble/issues/2072), we should add a `required` attribute to each input control that enables or disables the display of the visual state.

Need compatibility with existing [Angular form validation patterns](https://angular.io/guide/form-validation).

## 📋 Tasks

- [x] Visual design [link](https://www.figma.com/design/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?node-id=1295-47481)
- [ ] input control custom element changes
- [ ] input control unit tests
- [ ] input control Storybook tests
- [ ] input control Storybook docs
- [ ] input control Angular wrapper
- [ ] input control Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app

**Comment by jattasNI** [comment]
This is available for someone to start researching. The ultimate goal is an HLD. That will likely be quick to research and write but if not, Fred would appriciate an earlier high-level estimate once we have an initial idea of how hard it will be.

**Comment by NIbokeefe** [comment]
@fredvisser @jattasNI  @rajsite 

The request from visual design was to convert the Asterisk symbol from a font character into a vector path icon. 

-The icon is to be cropped to size 
-Provide alignment spec


Alignment of Asterisk with control label:

![Image](https://github.com/user-attachments/assets/b7b7e813-043c-408e-8336-3f0115623b9a)

**asterisk_5x5**
Tag: star, required, 

![Image](https://github.com/user-attachments/assets/8a6fa54c-249c-4218-9044-0d13f49a1a2b)

**Comment by m-akinc** [comment]
The Nimble support for this is complete, thanks to Molly.
