### ISSUE TITLE
Table cell error states

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#2101]
# 🙋 Feature Request

## 😯 Problem to Solve

Per #1776 

With user generated content, the table needs the ability represent that one or more table data cells are invalid.

For example:

- A column is configured to display numeric data, but some rows contain string data.
- A column is configured to display 'hyperlinks', but some rows contain external or poorly formated links.

In each case, we need to inform the user that the is an issue parsing or formatting the data and how they can resolve it.

Today, columns like the custom property column use placeholder text to show error strings. We should have a first class way to show this information.

![image](https://github.com/ni/nimble/assets/1458528/7f688f8b-85dc-4168-896b-8ff91a5c6536)

![Screenshot 2024-05-13 at 11 06 46 AM](https://github.com/ni/nimble/assets/1458528/00e683f4-0c2a-410e-b66b-8f1cc9a693c0)

- Need a visual representation that there is an issue/error with the data in the cell.
- Need a way for users to learn more about the nature of the error.
- Null or no values will not typically display with an error (instead will use placeholder text), but should be supported for future use cases.

## 💁 Proposed Solution

TBD

## 📋 Tasks

- [x] nimble-table [visual design spec update](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=5453-19325&mode=design)
- [ ] nimble-table spec update
- [ ] nimble-table custom element update
- [ ] nimble-table unit test update
- [ ] nimble-table Storybook test update
- [ ] nimble-table Storybook doc update
- [ ] nimble-table Angular wrapper update
- [ ] nimble-table Blazor wrapper update
- [ ] Update Angular example app
- [ ] Update Blazor example app
