### ISSUE TITLE
Built-in label for select and combobox

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#2183]
# 🙋 Feature Request

## 😯 Problem to Solve

(Copied from [AzDO feature](https://ni.visualstudio.com/DevCentral/_workitems/edit/2688093))
Most Nimble controls offer built in labels but select and combobox don't, meaning clients have had to create and style labels manually.

This will also resolve some accessibility bugs:
https://github.com/ni/nimble/issues/94
https://github.com/ni/nimble/issues/280

## 💁 Proposed Solution

We should update their templates to include labels, document the feature (hopefully including guidance about when to use labels and when not), and coordinate changing client apps to use the feature.

## 📋 Tasks

- [x] HLD
- [x] Implementation in nimble-components
- [ ] Determine best way to document feature / provide usage guidance (work with @fredvisser on this)
   - Related questions from Jesse on PRs:
       - Should it always be provided? Only provided if the purpose of the control isn't obvious from its placeholder / default value? Do we need a way to provide it for a screen reader but not show it visibly?
       - Label vs placeholder vs neither
    - Team discussion 8/16: General guidance will be a label should always be provided, and placeholder shouldn't be used instead of the label. Still needs to be documented somewhere though.
- [x] Publicize feature: SLE demo meeting in SLE demos and/or UI Working Group
- [x] Publicize feature: UI Working Group
   - @jattasNI will add something on UIWG agenda about it
- [x] Come up with list of systemlink-lib-angular usages that need to be updated
   - https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/777610
