### ISSUE TITLE
nimble-switch Component

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#292]
## 😯 Problem to Solve

Need to create a new nimble-switch component. 

## 💁 Proposed Solution

Should be able to use a fast-foundation switch class without any modification. Switch needs to be styled like the following visual design.

- FAST component: https://explore.fast.design/components/fast-switch
- Visual Design: https://xd.adobe.com/view/8ce280ab-1559-4961-945c-182955c7780b-d9b1/screen/3698340b-8162-4e5d-bf7a-20194612b3a7/variables/

![image](https://user-images.githubusercontent.com/7282195/151619387-5db537be-bdf2-470e-ab0a-f894934bf4f9.png)

## 📋 Tasks

- [x] nimble-switch spec
- [ ] nimble-switch custom element
- [ ] nimble-switch unit tests
- [ ] nimble-switch Storybook tests
- [ ] nimble-switch Storybook docs
- [ ] nimble-switch Angular wrapper
- [ ] Add to Angular example app
- [x] Update Component Status table in README

## Related PRs

1. #403 
2. #424 
3. #432

**Comment by nate-ni** [comment]
Duplicate of #387
