### ISSUE TITLE
nimble-date-time-text Component

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#294]
## 😯 Problem to Solve

Need to create a new Nimble component to display dates and times with consistent formatting (component name is open for debate). This was requested by the Transportation BU (screenshot below; contact Jonathan Meyer or Deborah Bryant for more info) but could be useful in other places.

## 💁 Proposed Solution

GitHub built some elements that we may be able to leverage: https://github.com/github/time-elements

- Visual Design: not requested yet

![image](https://user-images.githubusercontent.com/7282195/151620884-ec239abf-0e06-4689-a0d5-ce4aba0c4173.png)

### Requirements/features
- duration (3 minutes), absolute time (3:00, November 2nd, 2021)
- display formatting including people-friendly options ("yesterday" or "5 minutes ago" or "just now")
- localization and regional formatting (12 vs 24 hour, YMD order, etc)

## 📋 Tasks

- [ ] nimble-date-time-text interaction design issue
- [ ] nimble-date-time-text interaction design spec
- [ ] nimble-date-time-text visual design issue
- [ ] nimble-date-time-text visual design spec
- [ ] nimble-date-time-text spec
- [ ] nimble-date-time-text custom element
- [ ] nimble-date-time-text unit tests
- [ ] nimble-date-time-text Storybook tests
- [ ] nimble-date-time-text Storybook docs
- [ ] nimble-date-time-text Angular wrapper
- [ ] nimble-date-time-text Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
- [ ] Update Component Status table in README and incubating status
