### ISSUE TITLE
nimble-slider Component

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#295]
## 😯 Problem to Solve

Need to create a new Nimble component to pick a numeric value within a specific range using mouse/keyboard. This was requested by the following teams but could also be useful in other places:
- the Outlier Detection app (trying to replicate some UIs in O+ desktop Portal; contact Andrew Dove)

## 💁 Proposed Solution

- FAST component: https://explore.fast.design/components/fast-slider
- Visual Design: not requested yet

### Requirements/features
- continuous or noncontinuous increment value
- different fill colors to reflect different statuses
- scale showing tick marks and labels
- an indication of current value as you drag the slider (e.g. a tooltip)

## 📋 Tasks

- [ ] nimble-slider interaction design issue
- [ ] nimble-slider interaction design spec
- [ ] nimble-slider visual design issue
- [ ] nimble-slider visual design spec
- [ ] nimble-slider spec
- [ ] nimble-slider custom element
- [ ] nimble-slider unit tests
- [ ] nimble-slider Storybook tests
- [ ] nimble-slider Storybook docs
- [ ] nimble-slider Angular wrapper
- [ ] nimble-slider Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
- [ ] Update Component Status table in README and incubating status

**Comment by fredvisser** [comment]
Don't have any current clients requesting this component. Closing as "not planned"
