### ISSUE TITLE
nimble-card Component

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#296]
## 😯 Problem to Solve

Need to create a new Nimble component to display other components within a card. This was requested by the following clients but could be useful in other places:
1. Transportation BU (1st screenshot below; contact Jonathan Meyer or Deborah Bryant for more info).
2. [SLE landing page](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/258105) (2nd screenshot below; contact Fred Visser, Mark Black, or Michael Brandt for more info)

## 💁 Proposed Solution

- FAST component: https://explore.fast.design/components/fast-card
- Visual Design: not requested yet

![image](https://user-images.githubusercontent.com/7282195/151621674-4135f8af-03fb-4733-a715-cff616a867df.png)
![image](https://user-images.githubusercontent.com/10500124/151622134-c9c197dc-3a6f-4d92-8436-f07cb4741378.png)
![image](https://github.com/ni/nimble/assets/10500124/7fabefbf-b9e6-4dc7-bd63-22acd606b3eb) from [this BTS wireframe](https://lucid.app/lucidspark/6669223f-be64-404c-9374-6971288459b5/edit?page=0_0&invitationId=inv_1b26b2fa-159b-4ce0-b696-e5ad27f6f2b7)

### Requirements/features
- visual styling like drop shadows
- slots to include arbitrary content
- future: higher level card layouts as a mobile-friendly representation of a data grid?

## 📋 Tasks

- [x] nimble-card visual design issue
- [x] nimble-card visual design spec
- [x] nimble-card spec
- [x] nimble-card custom element
- [x] nimble-card unit tests
- [x] nimble-card Storybook tests
- [x] nimble-card Storybook docs
- [x] nimble-card Angular wrapper
- [x] nimble-card Blazor wrapper
- [x] Add to Angular example app
- [x] Add to Blazor example app
- [x] Update Component Status table in README and incubating status
- [ ] nimble-card pattern/usage documentation

**Comment by jattasNI** [comment]
Remaining open questions are around usage guidance for cards vs accordions. Should cards ever be collapsible? If so, would they just be replaced by accordion or are there still independent purposes? Fred can start driving this as he has bandwidth and works more on usage docs in the coming months.
