### ISSUE TITLE
toggle-button-group Component

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#298]
## 😯 Problem to Solve

Nimble should have a component that places multiple icon toggle buttons close to each other and allows either exclusive selection or non-exclusive.

Note: this was previously called split-icon-button but I renamed it to distinguish from #1523 

## 💁 Proposed Solution

- Visual Design: https://xd.adobe.com/view/8ce280ab-1559-4961-945c-182955c7780b-d9b1/screen/d022d8af-22f4-4bf2-981c-1dc0c61afece

![image](https://user-images.githubusercontent.com/7282195/151623495-107b933b-07d9-4e81-9831-8df316ec86a8.png)

## 📋 Tasks

- [ ] nimble-split-icon-button interaction design issue
- [ ] nimble-split-icon-button interaction design spec
- [ ] nimble-split-icon-button visual design issue
- [ ] nimble-split-icon-button visual design spec
- [ ] nimble-split-icon-button spec
- [ ] nimble-split-icon-button custom element
- [ ] nimble-split-icon-button unit tests
- [ ] nimble-split-icon-button Storybook tests
- [ ] nimble-split-icon-button Storybook docs
- [ ] nimble-split-icon-button Angular wrapper
- [ ] nimble-split-icon-button Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
- [ ] Update Component Status table in README and incubating status
