### ISSUE TITLE
nimble-search-field Component

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#299]
## 😯 Problem to Solve

Nimble should have a search field.

## 💁 Proposed Solution

- Visual Design: https://xd.adobe.com/view/8ce280ab-1559-4961-945c-182955c7780b-d9b1/screen/842889a5-67ba-4350-91c1-55eee48f4fa2/
- https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?node-id=1507%3A44702&mode=dev

![image](https://user-images.githubusercontent.com/7282195/151624073-feb2ba0d-4698-40f0-ad53-18da979423ca.png)

## 📋 Tasks
- [ ] ~~nimble-search-field spec~~
- [ ] ~~nimble-search-field custom element~~
- [ ] ~~nimble-search-field unit tests~~
- [ ] nimble-search-field Storybook tests
- [ ] nimble-search-field Storybook docs
- [ ] ~~nimble-search-field Angular wrapper~~
- [ ] ~~Add to Angular example app~~
- [ ] ~~Update Component Status table in README~~

**Comment by nate-ni** [comment]
GM is requesting global instant, segmented search for SLE.

https://ni.visualstudio.com/DevCentral/_backlogs/backlog/PP%20SystemLink/Initiatives/?workitem=2232557

Contextualizable if not in a global area (like in a table).

**Comment by rajsite** [comment]
This UI has a tooltip / autocomplete / picker thing that is revealed when entering the search box:
![MicrosoftTeams-image (7)](https://github.com/ni/nimble/assets/1588923/0bd3e419-666e-4169-8bd8-d8583245e397)
From [demo meeting @ 22:46](https://nio365-my.sharepoint.com/:v:/r/personal/alex_kerezsi_ni_com/Documents/Recordings/SystemLink%20Biweekly%20Demos-20230720_135702-Meeting%20Recording.mp4?csf=1&web=1&e=ZjFqro)

**Comment by fredvisser** [comment]
Closing in favor of #2021
