### ISSUE TITLE
nimble-menu-button Component

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#300]
## 😯 Problem to Solve

A menu button would be of general benefit to clients.

## 💁 Proposed Solution

We have [requested that FAST provide a menu-button](https://github.com/microsoft/fast/issues/5469). Once the FAST component exists, we can create the Nimble equivalent.

- FAST component: does not yet exist
- Visual Design: not yet requested

## 📋 Tasks

- [x] nimble-menu-button spec
- [x] nimble-menu-button custom element
- [x] nimble-menu-button unit tests
- [x] nimble-menu-button Storybook tests
- [x] nimble-menu-button Storybook docs
- [x] nimble-menu-button Angular wrapper
- [x] Add to Angular example app
- [x] Update Component Status table in README
