### ISSUE TITLE
nimble-banner Component

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#305]
## 👩🏽‍🤝‍👩🏼👨🏻‍🤝‍👨🏾 Feature Team
Feature Lead: @m-akinc 
Feature Tech Lead: @jattasNI 
Feature Manager: @fredvisser 
Product Manager: @nate-ni 
IxD: @leslieab 
ViD: @NIbokeefe 

## 😯 Problem to Solve
We need a banner to provide information to the user.

For ease of use, the banner should be simply configured without requiring knowledge of the Nimble Design token system or the need to hardcode design information into the instance of the component (colors, sizing, etc.).

This feature is for more persistent/static notifications. There is another component (currently called toast) that would be used for a temporary, overlay style notifications.

### In scope
- The banner will support common design system features (theme awareness, multi-platform support, etc.)
- The user should be able to easily configure a severity level/variant for the banner  - Error, Warning, Info, Neutral/None (Default)
- The user should be able to easily configure whether or not the banner is dismissible. 
- More than one banner should be able to be displayed at a time.

### Out of scope
Supporting arbitrary content in the banner.

### Open questions
| **Question**                                                            | **Initial Recommendation**                  | **Answer** | **Resolved** |
|-------------------------------------------------------------------------|-------------------------------------|------------|--------------|
| Do we need to support links or button(s) in the banner or is just text? | Unless there are existing needs, No | Yes        | Yes          |
| Do we need to support raw HTML?                                         | No                                  | No         | Yes          |
| Do we need to provide a "container" for multiple banners?               | No                                  |    No       |  Yes            |

### Banners references from other Design Systems
https://spectrum.adobe.com/page/alert-banner/
https://carbondesignsystem.com/components/notification/usage/
https://atlassian.design/components/banner/examples

### Some examples of banner screenshots
![Banner-Example-1](https://user-images.githubusercontent.com/109235103/211587994-fac688da-a934-4af5-aa92-473c9a348052.png)

![image](https://user-images.githubusercontent.com/109235103/211588179-0f9f11b4-7313-44b5-b5c3-326745e2f884.png)

![image](https://user-images.githubusercontent.com/109235103/211589403-85802799-0b61-4f62-9342-3643ae3a1491.png)

![image](https://user-images.githubusercontent.com/109235103/211621414-28721df9-d4ec-4cff-9768-ed55e34e174e.png)

![SL-Example](https://user-images.githubusercontent.com/109235103/211623992-e27e2432-a119-4b0e-9e3b-26df7de15fde.png)

![Image](https://user-images.githubusercontent.com/109235103/211858732-7dd85c35-493a-4f40-a407-5ba281f35938.png)

![image](https://user-images.githubusercontent.com/109235103/212177172-62e83ce3-dbee-4374-a7ad-96b2bfaaf68a.png)

### Visual Design
- #724
### Accessibility Considerations
Consider ARIA live regions for this component
https://web.dev/learn/accessibility/javascript/#page-level-2
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

```[tasklist]
## 📋 Tasks
- [x] Open questions resolved
- [x] #724
- [ ] #994 
- [x] nimble-banner  custom element
- [x] nimble-banner  unit tests
- [x] nimble-banner  Storybook tests
- [x] nimble-banner  Storybook docs
- [x] nimble-banner  Angular wrapper
- [x] Add to Angular example app
- [x] nimble-banner  Blazor wrapper
- [x] Add to Blazor example app
- [x] Update Component Status table in README
```
```[tasklist]
## Related PRs
- [ ] #994
- [ ] #1036 
- [ ] https://github.com/ni/nimble/pull/1063
- [ ] https://github.com/ni/nimble/pull/1062
- [ ] #1065
```

**Comment by mollykreis** [comment]
@nate-ni, your current recommendation is not supporting arbitrary content in the banner, but my initial reaction is that limiting to purely string content is too prohibited. In fact, most of the screenshots you show as examples have additional content. I think a common use case will be putting a link in the banner to get extra help or more information. Therefore, I think we should let clients put more content, such as anchors, within their banner.

**Comment by jattasNI** [comment]
>Do we need to support links or button(s) in the banner or is just text?

I found one example in SLS where a banner contained a link ([source](https://ni.visualstudio.com/DevCentral/_workitems/edit/1699828)). 
![image](https://user-images.githubusercontent.com/10500124/212174235-7c37be52-69d5-4925-b1c9-a3c6aa0c6c71.png)

It would be worth checking with the PM or UX designer for SLE licensing to see if [the SLE Licensing feature](https://dev.azure.com/ni/DevCentral/_search?text=license%20expire%20sle%20notification%2A&type=workitem&lp=workitems-Project&filters=Projects%7BDevCentral%7D&pageSize=25) has a similar requirement.

**Comment by nate-ni** [comment]
It's great to see an example. Translating that to the nimble banner would probably like:

If we provide a version with link or button for the action.
*Text* - "The SystemLinkServer - Advanced license...yada...will be archived."
*Link or Button* - "Learn more"
*Close* - True (This would take the place of the OK button)

**Comment by nate-ni** [comment]
> 

@mollykreis, thanks for the input. We have added the ability to provide a link or command into the banner. From the visual design, urls will get presented as links and commands will get presented as a button. We'll only support one for now, I believe, but can definitely expand on that in the future if needed.
