### ISSUE TITLE
nimble-text-area Component

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#314]
## 😯 Problem to Solve

TODO

## 💁 Proposed Solution

TODO
- FAST component: 
- Visual Design: 

## 📋 Tasks

- [ ] nimble-text-area spec
- [ ] nimble-text-area custom element
- [ ] nimble-text-area unit tests
- [ ] nimble-text-area Storybook tests
- [ ] nimble-text-area Storybook docs
- [ ] nimble-text-area Angular wrapper
- [ ] Add to Angular example app
- [ ] Update Component Status table in README
