### ISSUE TITLE
nimble-anchor Component (aka hyperlink or link button)

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#324]
## 😯 Problem to Solve

Need `nimble-anchor` to create theme-aware hyperlinks without requiring client apps to leverage a bunch of tokens. Also, it lets us create hyperlinks that appear as buttons, which is much better than abusing buttons for the same purpose (e.g. have browser security features like showing you the url on hover and open in new tab).

## 💁 Proposed Solution

- FAST component: https://explore.fast.design/components/fast-anchor
- Visual Design: [spec now available](https://xd.adobe.com/view/33ffad4a-eb2c-4241-b8c5-ebfff1faf6f6-66ac/screen/bfadf499-caf5-4ca0-9814-e777fbae0d46/) & [additional details about link typography](https://xd.adobe.com/view/8ce280ab-1559-4961-945c-182955c7780b-d9b1/screen/ceabc827-c080-405e-b34d-aa50e4f1e15f/)

We probably need tokens for the different link states in the different themes.
Link states:

- placeholder (ie link w/o href, <a>placeholder link</a>) assume we would just make it look like normal text?
- a:link (ie normal link w/ href, but unvisited)
- a:visited (ie normal link w/ href, but visited)
- :hover, :active and :focus states.

May share styles with Nimble breadcrumb component #343 

## 📋 Tasks

- [x] nimble-{name} spec
- [x] nimble-{name} custom element
- [x] nimble-{name} unit tests
- [x] nimble-{name} Storybook tests
- [x] nimble-{name} Storybook docs
- [x] nimble-{name} Angular wrapper
- [x] Add to Angular example app
- [x] nimble-{name} Blazor wrapper
- [x] Add to Blazor example app
- [x] Update Component Status table in README

### Related PRs
1. #832 
2. #918
3. #936 
4. #940

**Comment by nate-ni** [comment]
Re-opening until all related PRs are merged.
