### ISSUE TITLE
nimble-text-area Component

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#328]
## 😯 Problem to Solve

Nimble could use a multi-line text area component. It is needed to replace a native `textarea` control in the `sl-properties-list` component.

## 💁 Proposed Solution

- FAST component: https://explore.fast.design/components/fast-text-area
- Visual Design: https://xd.adobe.com/view/8ce280ab-1559-4961-945c-182955c7780b-d9b1/screen/7c146e4b-c7c9-4975-a158-10e6093c522d/

## 📋 Tasks
- [x] nimble-text-area spec
- [x] nimble-text-area custom element
- [x] nimble-text-area unit tests
- [x] nimble-text-area Storybook tests
- [x] nimble-text-area Storybook docs
- [x] nimble-text-area Angular wrapper
- [x] Add to Angular example app
- [x] Update Component Status table in README
