### ISSUE TITLE
nimble-date-picker Component

### ISSUE THREAD

**Issue by vikisekarNI** [ni/nimble#342]
## 😯 Problem to Solve

To conveniently pick a date through a date-picker input. This comes from one of HLD requirement's in Argon [here](https://ni.visualstudio.com/DevCentral/_git/srd-semi-ses-software/pullrequest/262099)

- User should be able to see a small calendar icon to the right of date input
- User should be able to select a date from the expanded calendar view. He/she should be able to scroll through days, months and years
- User should be able to type in the date in a standard format. For ex: DD/MM/YYYY

![image](https://user-images.githubusercontent.com/94439533/153158753-3f91bf13-c166-4854-9a66-cd132cd18b9c.png)

[Adobe XD View](https://xd.adobe.com/view/ee317991-74e3-4c8f-62aa-dd7512dc7951-9800/screen/440f5af5-d7e6-4bc8-b46d-e0d8ff984406/specs/) - Password: Soliton@123 – Reach out to Roshan(roshan.raju@ni.com) / John Nakano (john.nakano@ni.com) for getting Adobe XD Design files

## 💁 Proposed Solution
**Design** 
- #842  

Create a nimble date picker component. Inspired from [Material's Date Picker](https://material.angular.io/components/datepicker/overview)

## 📋 Tasks

- #2293 
- [ ] nimble-date-picker interaction design issue
- [ ] nimble-date-picker interaction design spec
- [ ] nimble-date-picker visual design issue
- [ ] nimble-date-picker visual design spec
- [ ] nimble-date-picker spec
- [ ] nimble-date-picker custom element
- [ ] nimble-date-picker unit tests
- [ ] nimble-date-picker Storybook tests
- [ ] nimble-date-picker Storybook docs
- [ ] nimble-date-picker Angular wrapper
- [ ] nimble-date-picker Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
- [ ] Update Component Status table in README and incubating status

**Comment by jattasNI** [comment]
Florina from the team that owns the SLE Executions and Routines apps reached out with another use case for the date picker. For Q4 featre [F1881164](https://ni.visualstudio.com/DevCentral/_backlogs/backlog/ASW%20SystemLink%20Sys%20Management/Features/?workitem=1881164) (Time-triggered routines frontend) they need to be able to pick a date and time that a job will run.
<img width="585" alt="image" src="https://user-images.githubusercontent.com/10500124/192325412-19b244d7-59d9-4ca5-b641-cd251836cc79.png">

That screenshot comes from [Leslie's wireframe](https://nio365-my.sharepoint.com/personal/leslie_bloomfield_ni_com/Documents/Microsoft%20Teams%20Chat%20Files/Executions%20%26%20Routines%20-%20Time.pdf) so hopefully she can provide more detailed requirements for this use case.

**Comment by jattasNI** [comment]
Update on the UI in the comment above: as a workaround while they wait for the Nimble date/time picker they ended up using a single component (from Angular Material) that allows selecting both date and time. They'd likely prefer separate components in order to match the wire frame above. More conversation in [this HLD PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/372687).

**Comment by jattasNI** [comment]
[Here's an interesting thread](https://gist.github.com/RobertAKARobin/850a408e04d5414e67d308a2b5847378) going deep on the pros and cons of native date pickers and calendar controls for picking dates. The author ended up deciding to use three separate inputs to enter a date on their site (select for month, numeric text for day and year). Looks like the [UK.gov design system](https://design-system.service.gov.uk/components/date-input/) linked in the comments made a similar choice. I'm not saying this conclusion applies to us, just reminding us that there are ways to enter a date that don't involve a calendar and we should consider what types of dates we'll be requesting from our users.

**Comment by nate-ni** [comment]
> just reminding us that there are ways to enter a date that don't involve a calendar and we should consider what types of dates we'll be requesting from our users.

100%. I try to create a separation between absolute dates (e.g. birth date, expiration date, etc.) and relative dates (e.g. whatever date next Thursday is, a Sunday in mid-March, etc.). "Absolute" and "Relative" may not be the best terms here but I don't have a better set right now.

For the first, the separate pickers/inputs is a good solution. For the latter, a calendar view is very helpful, if not required. 

I imagine both are relevant for our clients depending on their context/app and we'll have to see what component (or set of components) will support it well.

**Comment by jattasNI** [comment]
This came up again in a request from an NI partner developing SystemLink plugins using Nimble. Their current workaround is to use a Nimble text field with `textField.elementRef.nativeElement.control.type = 'date';` which actually gets the job done but doesn't have styling for the calendar.

![image](https://github.com/ni/nimble/assets/10500124/ea32f564-28c0-41c3-947b-aa8ff4924acc)

**Comment by SPathani-NI** [comment]
I would also like this component for my use case.
Currently I am also using the hack mentioned above, however it still gives its output in type "string" which the user has to manually extract to type "Date".

**Comment by jattasNI** [comment]
Removing the 'blocked' label because we don't plan to wait on FAST to implement this. No change in its priority for now, but we are not blocked from proceeding.

**Comment by atmgrifter00** [comment]
Another possible options is [Cally](https://wicky.nillia.ms/cally/), which is a pretty lightweight option, but allows fairly easy styling and slotting for certain things like using Nimble buttons for the 'Next' and 'Previous' buttons to move between months. It could be missing features that we ultimately want, like a dropdown to move between years, etc..., but it's worth considering.

[Here](https://github.com/ni/nimble/tree/cally-date-picker) is an early prototype branch ([link](https://60e89457a987cf003efc0a5b-rwvlfpjeti.chromatic.com/example-client-app/#/customapp) to working Angular example).

**Comment by jattasNI** [comment]
Some folks from the SLE Asset Management team mentioned they need a date picker for a workflow for scheduling calibration. They are having problems with the material-based wrappers in the Stratus shared library because their form integration isn't great; for example if you enter an invallid date the value change event fires before the validity change event, so change handlers have to handle the possibility that the value is invalid.

Just a reminder to consider form integration as part of our requirements and to add this to our list of reasons to prioritize this feature.
