### ISSUE TITLE
nimble-breadcrumb Component

### ISSUE THREAD

**Issue by msmithNI** [ni/nimble#343]
## 😯 Problem to Solve

Will be used by [SystemLink sl-breadcrumb-bar (AzDo F1792531)](https://dev.azure.com/ni/DevCentral/_workitems/edit/1792531)

## 💁 Proposed Solution

Extension of FAST Breadcrumb plus specific Angular integration for RouterLink.

**See [full spec for Nimble breadcrumb](https://github.com/ni/nimble/blob/main/packages/nimble-components/src/breadcrumb/breadcrumb.spec.md) for more information**

- FAST component: [fast-breadcrumb](https://explore.fast.design/components/fast-breadcrumb)
- Visual Design: [WIP](https://xd.adobe.com/view/8ce280ab-1559-4961-945c-182955c7780b-d9b1/screen/7b53bb3e-439b-4f13-9d5f-55adc7da8a2e/specs/) & [basic link spec](https://xd.adobe.com/view/8ce280ab-1559-4961-945c-182955c7780b-d9b1/screen/ceabc827-c080-405e-b34d-aa50e4f1e15f/)

Shared styles/ Angular directives with planned Nimble anchor component #324 

## 📋 Tasks

- [x] nimble-{name} spec
- [x] nimble-{name} custom element
- [x] nimble-{name} unit tests
- [x] nimble-{name} Storybook tests
- [x] nimble-{name} Storybook docs
- [x] nimble-{name} Angular wrapper (specific work needed for RouterLink, see spec)
- [x] Add to Angular example app
- [x] Come up with client API (CSS class on nimble-breadcrumb?) to choose whether link text is black or green when not hover/active. Default will be black. Active/mousedown state will be whichever other color was not the default state (i.e. black->green or green->black).
- [x] Finalize and integrate breadcrumb styling from UI/UX
- [x] Update Component Status table in README
