### ISSUE TITLE
nimble-spinner

### ISSUE THREAD

**Issue by gokulakrishnan-ni** [ni/nimble#346]
## 😯 Problem to Solve

Need a loading spinner to show during loading/fetching state in the application

### Design
- #822

The sizes shall be 16, 32, & 64.
@16x16 (8px squares)
@32x32 (16px squares)
@64x64 (32px squares)

### Storybook/Documentation
[Spinner Storybook page](https://nimble.ni.dev/storybook/?path=/docs/spinner--spinner)

## 📋 Tasks

- [x] #837 
- [x] nimble-spinner custom element (#920)
- [x] nimble-spinner unit tests (#920)
- [x] nimble-spinner Storybook tests (#920)
- [x] nimble-spinner Storybook docs (#920)
- [x] nimble-spinner Angular wrapper
- [x] nimble-spinner Blazor wrapper
- [x] Add to Angular example app
- [x] Add to Blazor example app
- [x] Update Component Status table in README

NOTE: The squares should spin clockwise.

### Related PRs
1. #837 
2. #920 
3. #926 
4. #950 
5. #988

**Comment by nate-ni** [comment]
Adding usage example that show the spinner being included in a small space. In this case...a part of a cell in a table.


![Image](https://user-images.githubusercontent.com/109235103/195620819-c54d7904-882a-414a-bb5c-5c7262040886.png)

**Comment by NIbokeefe** [comment]
Morning All,

I've reworked our brand version of the bits-indeterminate-spinner, and included them into Nimble components.

**Please take a look at the XD spec and let me know if this will cover what we need for production, and if you have any additional questions or feedback.**

- 16, 32 and 64 size examples
- Multiple UI color themes
- Animation timing
- Determinate version TBD
- Lets use this design universally for all indeterminate instances, which will help keep brand consistency. Unless there is a proposal (now or in the future) that provides a specific use case where this 'bits' indeterminate spinner will not work; meaning it's a UX issue for the user.

Navigate: Miscellaneous > Spinner - Indeterminate

https://xd.adobe.com/view/33ffad4a-eb2c-4241-b8c5-ebfff1faf6f6-66ac/

**Comment by nate-ni** [comment]
An example of on that was made already:
https://user-images.githubusercontent.com/109235103/204301521-56fb4a2b-a1e1-414f-ba53-c73b734edd4d.mov

**Comment by nate-ni** [comment]
Example of an indeterminate progress indication in a very small space (table cell)
https://user-images.githubusercontent.com/109235103/205939058-06310e61-3f64-433c-8821-57437641950f.mov

**Comment by jattasNI** [comment]
Here's another app (License modernization desktop UI) that needs a spinner very soon. Unclear whether it would be the bit spinner or a radial spinner. But it's being written in Blazor, so integration with that framework is important.

https://dev.azure.com/ni/DevCentral/_git/ASW/pullrequest/403221?_a=files&path=/Specs/License%20Management/Licensing%20Modernization/F2170385%20-%20Single%20Seat%20With%20Activation%20ID/Feature%20High%20Level%20Design.md

**Comment by msmithNI** [comment]
Spinner web component, and Angular + Blazor integration are now checked in. See Storybook page for notes on spinner sizing behavior.

[Spinner Storybook page](https://nimble.ni.dev/storybook/?path=/docs/spinner--spinner)

**Comment by nate-ni** [comment]
There are some open items remaining from the original feature request that need to be addressed.
