### ISSUE TITLE
Toggle switch

### ISSUE THREAD

**Issue by haworthia** [ni/nimble#387]
## 😯 Problem to Solve

My squad has a feature for which we need a slide toggle button. The UX spec includes the following:
![image](https://user-images.githubusercontent.com/32167177/155783949-40291acf-c5be-4437-9140-37fd4fd0b024.png)

The existing method to implement such as spec is the material slide-toggle-button. We'd like to avoid explicitly putting material components into our brand-new app.

## 💁 Proposed Solution

We would like the team to implement the [Toggle Switch from Brandon's Nimble Components spec](https://xd.adobe.com/view/8ce280ab-1559-4961-945c-182955c7780b-d9b1/screen/3698340b-8162-4e5d-bf7a-20194612b3a7/specs/).
![image](https://user-images.githubusercontent.com/32167177/155784711-8eb63e1e-edde-4775-afa0-e1661dd13b6e.png)

[FAST's switch](https://explore.fast.design/components/fast-switch) looks like a promising starting point.

## 📋 Tasks

- [x] nimble-switch spec
- [x] nimble-switch custom element
- [x] nimble-switch unit tests
- [x] nimble-switch Storybook tests
- [x] nimble-switch Storybook docs
- [x] nimble-{name} Angular wrapper
- [x] nimble-{name} Blazor wrapper
- [x] Add to Angular example app
- [x] Add to Blazor example app
- [x] Update Component Status table in README

## Related PRs

1. #403 
2. #424 
3. #432
