### ISSUE TITLE
nimble-toolbar Component

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#411]
## 😯 Problem to Solve

- sl-toolbar in systemlink-lib-angular
- possibly the header bar in systemlink-lib-angular

## 💁 Proposed Solution

- FAST component: https://explore.fast.design/components/fast-toolbar
- Visual Design: _None_

## 📋 Tasks

- [x] nimble-toolbar  spec
- [x] nimble-toolbar custom element
- [x] nimble-toolbar unit tests
- [x] nimble-toolbar Storybook tests
- [x] nimble-toolbar Storybook docs
- [x] nimble-toolbar Angular wrapper
- [x] Add to Angular example app
- [x] Update Component Status table in README

## Open issues with FAST
- https://github.com/microsoft/fast/issues/5723
- https://github.com/microsoft/fast/issues/5756
- https://github.com/microsoft/fast/issues/5121
