### ISSUE TITLE
nimble-picker Component

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#458]
## 😯 Problem to Solve

Create a component based on the FAST picker that shows selections from a list of options.

## 💁 Proposed Solution

- FAST component: https://github.com/microsoft/fast/tree/master/packages/web-components/fast-foundation/src/picker
Note that FAST component is currently in alpha phase, so there may be bugs/issues.
  - Alternatively, [Vivid solution](https://github.com/Vonage/vivid-3/blob/7dc2e2249768749b64392c62807e9b7493ed603b/libs/components/src/lib/tag/tag.ts) 
- Visual Design: [spec](https://www.figma.com/design/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?node-id=2227-78839)
- Needs to support adding "invalid" elements and a way to visually style them differently from "valid" elements. This can happen if a user selected a valid element but then the underlying list of valid items changes; we'd like to give users feedback that their selection is no longer valid rather than just removing the item automatically or leaving it shown as valid.

Looks something like this:

![Frame 9939](https://github.com/user-attachments/assets/dd4c9561-b9b2-44fb-935f-79b4f1c5913b)

or this from the [PDV app in SLE](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=/docs/design-documents/Test-Insights/Query-and-visualize-parametric-data.md&_a=preview):
![image](https://user-images.githubusercontent.com/99422861/230320904-4eb55fd0-5cbf-4803-b7ed-0b964d8a3f50.png)

## 📋 Tasks

- [ ] [nimble-picker interaction design issue](https://github.com/ni/nimble/issues/1214)
- [ ] nimble-picker interaction design spec
- [ ] [nimble-picker visual design issue](https://github.com/ni/nimble/issues/745)
- [ ] [nimble-picker visual design spec](https://www.figma.com/design/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?node-id=2227-78839)
- [ ] nimble-picker spec
- [ ] nimble-picker custom element
- [ ] nimble-picker unit tests
- [ ] nimble-picker Storybook tests
- [ ] nimble-picker Storybook docs
- [ ] nimble-picker Angular wrapper
- [ ] nimble-picker Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
- [ ] Update Component Status table in README

**Comment by jattasNI** [comment]
@ranjgith-ni provided more detail about use cases in #1164 which I'm copied to the description above. 

To answer the priority question from that issue: the Design System squad decided to mark this as "staging" for Cycle 2. This means we'll start working with designers on resolving open questions about the component behavior and appearance, but are not expecting to deliver the completed component. We've been hoping to delay development until FAST's picker component is more mature to save ourselves work. But if your squad is willing to invest in a custom implementation, we would be happy to talk about what that would entail.

**Comment by jattasNI** [comment]
Fred and I were brainstorming about picking from a hierarchical list of items, which is a requirement for the SLE Data Spaces app. If the hierarchy is only a single level (which it is for that use case) then it could be solved with the same mechanism as #791

![image](https://github.com/ni/nimble/assets/10500124/d4762d34-db8c-4467-ab62-c9bf467c5cb4)
![image](https://github.com/ni/nimble/assets/10500124/34a9715b-463d-4d3b-8d1d-c5acb19ef564)
![image](https://github.com/ni/nimble/assets/10500124/10fdedf6-292a-4819-8f59-b4bab170e7c7)

**Comment by jattasNI** [comment]
Another use case came up in [this SLE Routines HLD](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/758009?path=/docs/design-documents/Routines/Routine-service-roles.md&_a=files&anchor=5.-alternative-implementations-and-designs). They need to be able to multi-select workspaces. Their current proposal is to use [material select configured with multiselect](https://material.angular.io/components/select/overview) and [configure it to allow filtering](https://stackoverflow.com/questions/58747639/adding-search-functionality-in-mat-multiple-select-in-angular-material).

**Comment by jattasNI** [comment]
Another request for picker / tags came up in [a Teams thread about the Data Explorer app](https://teams.microsoft.com/l/message/19:Cb5zEPCpdADS7kC0XTWXJGwZCq0qHVxnjkiPEWeEz7k1@thread.tacv2/1730487742915?tenantId=eb06985d-06ca-4a17-81da-629ab99f6505&groupId=180bf0c7-4ff2-405e-8330-fdbe8ab6eb52&parentMessageId=1730487742915&teamName=TM-Design%20System&channelName=General&createdTime=1730487742915).

**Comment by kroeschl** [comment]
Chiming in that our internal Dashboard product would like a chip as well. Currently we're using `mat-chip` with a design that we made up, but we'd prefer something designed to match Nimble.

**Comment by jattasNI** [comment]
>Chiming in that our internal Dashboard product would like a chip as well.

@kroeschl heads up that @atmgrifter00 reopened a chip-specific issue #413 and started working on it #2667. Hopefully it will meet your needs and you can adopt it once it's ready. Please chime in on one of those PRs if you can identify any gaps.
