### ISSUE TITLE
nimble-combo-box Component

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#462]
## 😯 Problem to Solve

Create a combo-box control which allows filtering down a long list of selectable options.

This could be used by the SystemLink Enterprise workspace selector, though it currently has some non-standard behaviors where filtering the list by typing doesn't actually hide items which don't match.
![image](https://user-images.githubusercontent.com/10500124/160490433-466d562d-2ffb-4b15-a37b-04701765085a.png)

Related: #341 

## 💁 Proposed Solution

- FAST component: https://explore.fast.design/components/fast-combobox
- Visual Design: (marked WIP) https://xd.adobe.com/view/33ffad4a-eb2c-4241-b8c5-ebfff1faf6f6-66ac/screen/bd6755d9-8fd2-4b97-9709-939ea20680ae/

## 📋 Tasks

- [x] nimble-combobox spec
- [x] nimble-{name} custom element
- [x] nimble-{name} unit tests
- [x] nimble-{name} Storybook tests
- [x] nimble-{name} Storybook docs
- [x] nimble-{name} Angular wrapper
- [x] Add to Angular example app
- [x] Update Storybook docs for Combobox, Select, and MenuButton to outline reasons to use one over the other
- [x] Update Component Status table in README

## Future Work

- #507
- #486
- #535
