### ISSUE TITLE
Nimble navigation tabs

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#479]
## 😯 Problem to Solve

SLE apps need a nimble component to replace the [MatTabNav](https://material.angular.io/components/tabs/api#MatTabNav). This is a set of tabs, where clicking on the tab navigates rather than moving to pre-defined tab content.

One known use case for this is TestInsights [result-details.component](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=%2FWeb%2FWorkspaces%2FTestInsights%2Fsrc%2Fapp%2Fcomponents%2Fresult-details%2Fresult-details.component.html&_a=contents&version=GBmaster):
<img width="568" alt="image" src="https://user-images.githubusercontent.com/10500124/167954481-f2ca4737-e9d5-4024-9844-d012441f0c37.png">

## 💁 Proposed Solution
- #946

There are a number of open questions that should be considered when coming up with a solution:
- Is there a use-case to support normal tabs & navigation tabs together?
- Is this a mode of the existing tab panel or a new component?
- Should we base this on the FAST tab panel or create button styling that looks like tabs?
- What's the expected keyboard interaction?
    - Note: With the existing tab panel, the tabs switch using the arrow keys. For navigation tabs we would likely want to see the focused tab change with the arrow keys but not navigate until the user presses 'Enter'.

## 📋 Tasks
- [x] #938 
- [x] nimble-anchor-tab custom element (#960)
- [x] nimble-anchor-tab unit tests (#960)
- [x] nimble-anchor-tab Storybook tests (#960)
- [x] nimble-anchor-tab Storybook docs  (#960)
- [x] nimble-anchor-tab Angular wrapper (#987)
- [x] nimble-anchor-tab Blazor wrapper (#989)
- [x] Add to Angular example app (#987)
- [x] Add to Blazor example app (#989)
- [x] Update Component Status table in README (#960, #987, #989)

## Related PRs
- #938 
- #960 
- #987 
- #989

**Comment by nate-ni** [comment]
> Is there a use-case to support normal tabs & navigation tabs together?

Looking through the product there doesn't appear to be a case where they are mixed
[Link to search results](https://dev.azure.com/ni/DevCentral/_search?action=contents&text=mat-tab-nav-bar&type=code)

> Is this a mode of the existing tab panel or a new component?

I don't have a strong opinion on this. The element being replace (mat-tab-nav-bar) appears to be it's own element
[link to material tabs](https://material.angular.io/components/tabs/overview#tabs-and-navigation)

> Should we base this on the FAST tab panel or create button styling that looks like tabs?

Pass :)

> What's the expected keyboard interaction?

Google may have figured this one our for us as well
https://material.angular.io/components/tabs/overview#keyboard-interaction
