### ISSUE TITLE
nimble-query-builder Component

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#506]
## 😯 Problem to Solve

SLE is currently using the JQX query builder and  Soliton is using a query builder they made themselves. We need to gather requirements from both usages.

## 💁 Proposed Solution

- FAST component: 
- Visual Design: 

```[tasklist]
## 📋 Tasks
- [ ] nimble-query-builder design
- [ ] nimble-query-builder spec
- [ ] nimble-query-builder custom element
- [ ] nimble-query-builder unit tests
- [ ] nimble-query-builder Storybook tests
- [ ] nimble-query-builder Storybook docs
- [ ] nimble-query-builder Angular wrapper
- [ ] Add to Angular example app
- [ ] Update Component Status table in README
```

**Comment by nate-ni** [comment]
Design issue at #843

**Comment by jattasNI** [comment]
There's a discussion [on Teams](https://teams.microsoft.com/l/message/19:0c59ac4a4cc1438894cb42f4b21703f9@thread.skype/1672758890225?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=41626d4a-3f1f-49e2-abdc-f590be4a329d&parentMessageId=1672758890225&teamName=ASW%20SystemLink&channelName=UI%20Working%20Group&createdTime=1672758890225&allowXTenantAccess=false) about queries with very long values in enum selectors. In the existing query builder, the dropdown grows its width to fit the longest item which causes scrollbars on the containing slideout. It would be nice if the Nimble component supported this better . Here are some options but we should probably get UX input:
1. max width on the dropdown and truncate with an ellipsis. Preferably with a tooltip on hover to show the full value.
2. max width and horizontal scrollbar on the dropdown (that's what's currently being proposed in the linked discussion)
3. max width and wrap text
4. totally different UX like shortening the text or choosing a different component that reflects the contents of the text differently (maybe something hierarchical like a tree?)

(This might end up being a request for the select or combobox but tracking it here for now)

![image](https://user-images.githubusercontent.com/10500124/210594798-0e85d95e-4acd-4e9a-88d0-d4d3edb8b2b2.png)

**Comment by jattasNI** [comment]
[Teams post from Leslie](https://teams.microsoft.com/l/message/19:8e5f3e80de8146d5aaecdc2112e89191@thread.skype/1684186663649?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=41626d4a-3f1f-49e2-abdc-f590be4a329d&parentMessageId=1684186663649&teamName=ASW%20SystemLink&channelName=UX&createdTime=1684186663649) that collects some previous research and design specs.

**Comment by jattasNI** [comment]
There's [a discussion thread on an SLE PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/508729#1687901024) about ways for the query builder to dynamically populate the list of properties to select from based on an HTTP request. The current proposal is to hope that the request completes quickly so that users don't notice the list of items changing. It would be great if the Nimble query builder supported this in a more first class way. For example:
1. a place to show a spinner to indicate options are still being fetched
2. a combobox experience that allows the user to type an arbitrary value at any time but does more helpful autocomplete once the options have been fetched

This use case would also benefit from the grouped items feature described above to separate built-in properties from custom properties.

**Comment by jattasNI** [comment]
Some new requirements for querying by date ranges from [this SLE asset history HLD](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/533124?_a=files&path=/docs/design-documents/Asset/Asset-connection-history-monitoring.md). They still haven't decided what UX they want but it might end up being something like a control for picking start date and another for a duration. We should either support date ranges natively or allow extension for clients to provide a date range picker.

**Comment by jattasNI** [comment]
[SLE HLD discussion thread](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/671805#1710528872) about inputs for numeric clauses having a configurable number of decimal digits. If the query is filtering an integer field we shouldn't let the user enter fractional digits. And there may be use cases for showing a small number of decimal digits.

**Comment by jattasNI** [comment]
We briefly discussed query builder with SLE Systems and Assets teams. They mentioned some (hopefully well-known) requirements for the output format of the configured query:
1. need a way to convert it to LINQ since that is what services use today
2. also need a more abstract representation because there are longer term visions to move away from LINQ for some services. Hopefully there's a standard / common query representation we can rely on and not invent something ourselves.

**Comment by jattasNI** [comment]
Some more potential query builder requirements [in this SLE HLD for Grafana configuration](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/757640):
1. styling that matches other Grafana components
2. React support
3. possible new use cases / query types / layout requrements / LINQ support needs (nothing concrete, just a different type of use case than other SLE query building)
