### ISSUE TITLE
nimble-accordion Component

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#533]
## 😯 Problem to Solve

We want an accordion control which allows stacking several regions and allowing the user to collapse them to save space.

Here is an example in SystemLink Server's [package-viewer](https://ni.visualstudio.com/DevCentral/_git/Skyline?path=/Web/Workspaces/SystemsManagement/projects/systems/src/app/software/packages-viewer/packages-viewer.component.html), which uses mat-accordion. There is [a proposal](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/287607?_a=files&path=/Specs/Enterprise/Manage%20Notebook%20Execution%20Results/Specification.md) to bring this component to SLE for an app to manage notebook execution.
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/10500124/166562762-0585baae-b5d2-4053-aa6a-4242549c61a0.png">

## 💁 Proposed Solution

- FAST component: https://explore.fast.design/components/fast-accordion
- Visual Design: #778 

## 📋 Tasks

- [ ] nimble-accordion interaction design issue
- [ ] nimble-accordion interaction design spec
- [ ] nimble-accordion visual design issue
- [ ] nimble-accordion visual design spec
- [ ] #784
- [ ] nimble-accordion custom element
- [ ] nimble-accordion unit tests
- [ ] nimble-accordion Storybook tests
- [ ] nimble-accordion Storybook docs
- [ ] nimble-accordion Angular wrapper
- [ ] nimble-accordion Blazor wrapper
- [ ] Add to Angular example app
- [ ] Update Component Status table in README and incubating status

**Comment by jattasNI** [comment]
Another client [needs this](https://teams.microsoft.com/l/message/19:0c59ac4a4cc1438894cb42f4b21703f9@thread.skype/1664802527322?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=41626d4a-3f1f-49e2-abdc-f590be4a329d&parentMessageId=1664802527322&teamName=ASW%20SystemLink&channelName=UI%20Working%20Group&createdTime=1664802527322&allowXTenantAccess=false) for the Steps and PDV workflow:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/10500124/193619709-63102f3d-8de1-4952-a5d8-72bb6e991607.png">

**Comment by jattasNI** [comment]
Linking to #1150 since it tracks generating usage documentation for when to use the accordion.

**Comment by aidendk** [comment]
Leaving notes for the prototype accordion implementation I've been working on as I'll be finishing my internship today:

I've started work on a prototype for the nimble-accordion, which can be found [in this branch](https://github.com/ni/nimble/tree/nimble-accordion). I've implemented the FAST component along with functionality for searching text inside of closed accordion items, appearance values that change every accordion item to the same appearance, an error-visible state for accordion items, and a disabled state. The expand mode has not yet been removed from the component, and instead relies on a function in the accordion index.ts that keeps the expand mode as `multi` regardless of the text value it has in the dev tools html attribute.

The disabled state is currently on the accordion-item, although it is unclear if we should allow one accordion item to be disabled and let other items in the accordion be active.

The styling for the accordion uses cascade layers with hierarchy, and is almost completely up to date with the designs in the Figma spec. However, these designs are outdated after a discussion regarding the placement of borders for the accordion as well as if accordion header appearances should be implemented. [See this comment for more info](https://github.com/ni/nimble/pull/1371#discussion_r1290669734). A MultiValuePropertyStyleSheetBehavior is currently used to apply different styles to the accordion items based on the appearance, and ::before pseudoelements for the accordion header and content sections are used to apply the border functionality correctly.

Tests have not yet been written, and Blazor / Angular integration has not been done.

Extras:
As of writing this, the accordion spec is still in progress. It can be found [here]().

I demoed a WIP prototype of the accordion at the Intern showcase and many people seemed interested in the ability to have only one accordion item open at a time (FAST's `single` expand mode). Before making a solid decision to only allow the `multi` expand mode, more research on use cases for the single expand mode from other websites could be beneficial. 

The design spec shows different types of nimble components inside accordions having specific heights, paddings, etc., but this functionality doesn't seem possible to implement as we don’t know what components users will put inside of the accordion.

Hopefully this helps a bit, and thanks to whoever picks up the accordion! 😄

**Comment by SPathani-NI** [comment]
I also need this component to replicate https://dashboard.ni.systems/dashboard/#/systems/system-logs (Log Retrieval Controls )

**Comment by atmgrifter00** [comment]
> I also need this component to replicate https://dashboard.ni.systems/dashboard/#/systems/system-logs (Log Retrieval Controls )

Could you provide a screenshot of what you are referring to? The provided link does not work for me.

**Comment by jattasNI** [comment]
@atmgrifter00 you have to be on the NI network to view that app. Here are screenshots of the Log Retrieval Controls pane expanded and collapsed. 

<img width="1504" alt="image" src="https://github.com/ni/nimble/assets/10500124/5bdcfe63-9bd4-49d6-a4df-5a7eee65a448">

<img width="1504" alt="image" src="https://github.com/ni/nimble/assets/10500124/a504d0b6-6e2d-40f4-999b-a17cc76c6c86">

**Comment by SPathani-NI** [comment]
My main concern is the presence of component itself as right now without it we have to either use CSS based hiding which is not visually pleasing or use material component which we want to limit as much as possible.
For my use case only the basic features would be enough.

**Comment by jattasNI** [comment]
Two more clients have implemented an accordion within their apps recently:

1. SLE Routines create routine slide out is [using the native summary/detail](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=/Web/Workspaces/RoutineManager/src/app/components/create-routine/create-routine.component.html&version=GBmaster&line=11&lineEnd=12&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)
2. the Blazor chat shared component built one too
