### ISSUE TITLE
nimble-stepper (wizard) Component

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#624]
## 😯 Problem to Solve

Some UIs want to provide a guided way to navigate through multiple screens and see which step of the navigation they're on. 

Gergo described this workflow [in this Teams thread](https://teams.microsoft.com/l/message/19:0c59ac4a4cc1438894cb42f4b21703f9@thread.skype/1655990140928?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=41626d4a-3f1f-49e2-abdc-f590be4a329d&parentMessageId=1655990140928&teamName=ASW%20SystemLink&channelName=UI%20Working%20Group&createdTime=1655990140928). We discussed it with designers [in this Teams thread](https://teams.microsoft.com/l/message/19:8e5f3e80de8146d5aaecdc2112e89191@thread.skype/1656081236979?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=41626d4a-3f1f-49e2-abdc-f590be4a329d&parentMessageId=1656081236979&teamName=ASW%20SystemLink&channelName=UX&createdTime=1656081236979). Current wireframes use a tab control with app-provided Next/Previous buttons as an additional way to advance to the next tab.

This seems like it will be a common pattern in desktop apps that present a wizard experience, like an installer.

## 💁 Proposed Solution

We haven't reached consensus with Design about whether this should be a shared component and what it might look like. Some options:
1. create a higher level component that provides a tab with next/previous buttons2. 
2. create a stepper that shows a unique UX with more progress information, similar to a [Material stepper](https://material.angular.io/components/stepper/overview)

<img width="676" alt="image" src="https://user-images.githubusercontent.com/10500124/178279038-7c64d0f1-1a6c-4a82-a0e5-d17ce3945006.png">

![Add Feeds  SystemLink Review](https://user-images.githubusercontent.com/10500124/178279299-816b1d51-c03b-4dcc-8bad-345f70d18b54.jpg)

## 📋 Tasks

- [ ] nimble-stepper interaction design issue
- [ ] nimble-stepper interaction design spec
- [ ] nimble-stepper visual design issue
- [ ] nimble-stepper visual design spec
- [ ] nimble-stepper spec
- [ ] nimble-stepper custom element
- [ ] nimble-stepper unit tests
- [ ] nimble-stepper Storybook tests
- [ ] nimble-stepper Storybook docs
- [ ] nimble-stepper Angular wrapper
- [ ] nimble-stepper Blazor wrapper
- [ ] Add to Angular example app
- [ ] Add to Blazor example app
- [ ] Update Component Status table in README and incubating status

**Comment by jattasNI** [comment]
[Thread on an SLE PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/518352#1689002306) discussing wizard UX within drawers. There are a couple existing instances that built their own pattern but it is becoming more prevalent so we might want a shared component to provide more consistent UX and implementation pattern.

**Comment by jattasNI** [comment]
A request for a stepper came up in a [Teams conversation about Data Explorer](https://teams.microsoft.com/l/message/19:Cb5zEPCpdADS7kC0XTWXJGwZCq0qHVxnjkiPEWeEz7k1@thread.tacv2/1730487742915?tenantId=eb06985d-06ca-4a17-81da-629ab99f6505&groupId=180bf0c7-4ff2-405e-8330-fdbe8ab6eb52&parentMessageId=1730487742915&teamName=TM-Design%20System&channelName=General&createdTime=1730487742915). Their initial proposal is to use the Material stepper styled with Nimble tokens.

**Comment by jattasNI** [comment]
Here's how the Data Explorer stepper turned out

<img width="1102" height="822" alt="Image" src="https://github.com/user-attachments/assets/d584dc7c-bcb7-4c79-84c4-ff636063f41c" />
