### ISSUE TITLE
Set up Blazor end-to-end tests

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#705]
## 🧹 Tech Debt

We should have infrastructure (presumably Playwright) for running e2e tests in order to fill testing gaps that are difficult to test via unit tests and Chromatic. This came up in the context of writing unit tests for the Nimble dialog's Blazor integration. The Blazor implementation of the dialog calls js using the JSRuntime, but BUnit tests don't support that. This made it impossible to test that part of the Blazor implementation. 

## Tasks
- [ ] Tests for hover / focus states. We tried to test this with Chromatic but ran into issues (see #495)
- [x] Blazor e2e/acceptance test infrastructure using Playwright, add initial tests: #1248
- [ ] Add additional Blazor acceptance tests to fully test `NimbleBlazor.lib.module.js` and other functionality not covered by unit tests: https://github.com/ni/nimble/issues/1804

**Comment by jattasNI** [comment]
@atmgrifter00 can you update this tech debt item with any info/links/lessons learned from when you investigated it in your CI week?

**Comment by atmgrifter00** [comment]
I got as far as creating a branch in Blazor that has the Playwright infrastructure set up, with a dummy test. However, at the moment, the `PlaywrightFixture` test fixture class isn't being called to properly set up the local run with the proper Chromium version to run. Some investigation is needed to figure out what is missing. My guess is that there is only a little more work needed to get to where we can write a component e2e test in Blazor.
