### ISSUE TITLE
nimble.ni.dev landing page improvements

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#804]
## 😯 Problem to Solve

We've started building https://nimble.ni.dev in a scrappy way but as we build the real deal that UX designs for #771, we should make it more production ready. This issue tracks some ideas we've had.

## 💁 Proposed Solution

See task list below. Feel free to add more.

## 📋 Tasks
- [x] TypeScript, SCSS, build tooling - addressed by #852
- [x] Apply linting or prettier to the CSS
- [x] Deploy it as part of the PR pipeline like we do with storybook and example apps so we can preview changes in PR
- [ ] Run Chromatic tests so we can inspect diffs and maintain good Lighthouse scores (e.g. see #904 where we maintain this manually)

**Comment by rajsite** [comment]
Only remaining task is lighthouse and chromatic integration.
- I think chromatic integration is low roi as the page has lots of animations and it's most interesting aspect is responsive layout which are two things that are difficult to manage in chromatic
- Automated Lighthouse CI is low roi as it's rarely changing

If the landing page is revved more often or becomes more complex we can revisit the automation
