### ISSUE TITLE
Adopt visual design for wafer map

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#910]
## 😯 Problem to Solve

@RickA-NI (NI visual designer) produced some visual designs for wafer maps for a previous project. We should consider adopting them for the Nimble wafer map component.

## 💁 Proposed Solution

The designs are available in [this XD document](https://xd.adobe.com/view/94f91254-69b5-4164-8927-8dd6844e3959-c1aa/screen/226368a0-f6b6-48d9-b75c-41958c230b99/).

## 📋 Tasks
- [ ] provide the color palettes listed on page 54 (copied below). We could still allow users to provide their own palette but provide these two palettes as constants that they could pass to that input instead of building their own list. The one on the left would be given a name that implies it's default (it is more accessible to people with red-green color blindness). The one on the right could be another option (it is more traditional green=good, red=bad). These colors were only designed for a light theme so we eventually will want other palettes for dark theme, so they should have names that reflect this.
- [ ] the design doesn't specify a border or notch color, but Rick suggested using Black91 at 60% opacity. We would use the same color for all themes to start with.
- [ ] consider providing a rendering mode to hide the notch. The product that this design was produced for didn't require a notch/border. While that product isn't being worked on, others in the future may have the same requirement.
- [ ] ~~ensure spacing / rendering of the grid between dies matches the design spec (see image below)~~ Rick says the percentage-based approach which is already in use is good
- [ ] ~~(probably out of scope for now, but worth discussing) discuss decimation / aggregation strategy when number of dies exceeds the number of pixels available to render them~~ This can be deferred for now since initial use cases will have smaller amounts of data / larger amounts of space, not used in a gallery mode.

![image](https://user-images.githubusercontent.com/10500124/206759890-4e3fc17a-9469-492a-a44a-0311f97836ec.png)

![image](https://user-images.githubusercontent.com/10500124/206761075-704386df-3a9d-4bd4-bb9e-6a62121ddae1.png)

**Comment by jattasNI** [comment]
@zszilagy, @munteannatan, @elizaolariu, @DStavilaNI 

Let me know if you have thoughts about the suggestions in this issue. Do they seem reasonable to you? Will they fit within your time bandwidth?

We can also talk about it on a call next week. If you want to talk in detail about the designs, let me know in advance so I can invite Rick.
