### ISSUE TITLE
nimble-wafer-map Component

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#924]
## 💁 Proposed Solution

- FAST component: N/A
- Visual Design: #910 

```[tasklist]
## 📋 Tasks for release readiness
- [x] #805
- [x] `nimble-wafer-map` custom element
- [x] `nimble-wafer-map` unit tests
- [x] `nimble-wafer-map` Storybook tests
- [x] `nimble-wafer-map` Storybook docs
- [ ] `nimble-wafer-map` Storybook docs (needs a final pass)
- [ ] #964
- [x] Avoid recreating event listeners in every render, see discussion: https://github.com/ni/nimble/pull/1005#discussion_r1099287598
- [x] add NIR code owners for wafer-map directory
- [ ] update status table in README, remove usage warning from storybook, and start following semantic versioning
```

```[tasklist]
## Tasks post-release
- [ ] `nimble-wafer-map` Angular wrapper
- [x] `nimble-wafer-map` Blazor wrapper
- [ ] Add to Angular example app
- [x] Add to Blazor example app
- [ ] Accessibility/keyboard interactions
- [ ] #971
- [ ] #910
- [ ] Update Component Status table in README
```
```[tasklist]
## Related PRs
- [ ] #923
- [ ] #913 
- [ ] #909 
- [ ] #905 
- [ ] #835 
- [ ]  #831 
- [ ] #818 
- [ ]  #805 
- [ ]  #927
- [ ] #933
- [ ] #954 
- [ ] #968 
- [ ] #967 
- [ ] #1005 
- [ ] #1006 
- [ ] #1040
- [ ] #1057
- [ ] #1069
- [ ] https://github.com/ni/nimble/pull/1784
```

**Comment by jattasNI** [comment]
We discussed the long term plan to move this out of incubating as part of #2406. The proposal there is that this component belongs in the Spright package within the Nimble repo. It's not a reflection of the quality, completeness, or usefulness of the component, just that it is more special-purpose than typical Nimble components like text field and table.

The work involved would be to move the code from packages/nimble* to packages/spright* and move the stories to the Spright section of storybook. This would be a breaking change for clients as they would now import from spright-angular, SprightBlazor, or spright-components packages. We'd need to either update client apps or notify them to make the updates themselves.

@munteannatan @DStavilaNI What do you think of this proposal? If you like the direction, any chance your team would be interested in implementing that migration?
