### ISSUE TITLE
[DRAFT] - Update design tokens to include a spacing scale

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#959]
## 😯 Problem to Solve
As a Nimble user, I need to be able to provide spacing in my application that is consistent with the nimble design system. While this will be unnecessary for nimble components, it is necessary for custom components that should still be consistent with the Nimble Design System.

As a Nimble Developer, I need access to set of spacing values/tokens that can be used for creating new shared, nimble components.

These values are commonly used for padding and margins in styles but are useful anywhere spacing is needed (column gap in a css grid, for example)

## 💁 Proposed Solution
Create a set of context agnostic spacing tokens that can be accessed by Nimble and non-Nimble developers to provide consistent spacing in their applications, custom components and Nimble components.

Create a set of context specific tokens for relevant, existing uses of these design values.

### Accessibility Considerations
While there might be a need for some some non-responsive spacing sizes (0px, 1px, for example); other tokens should consider using responsive units (rem) to scale appropriately to accommodate for users that have adjusted their text size settings.

### Open Questions
What naming convention should be used for our base token set?
There is a broad array of these in other design systems and no standard practice to follow that I can identify.
- T-shirt size? (S, MD, XL, XXL, ...)
- Small integer (spacing-1, spacing-2, etc.)
- Small float (spacing-1, spacing-2.5, etc.)
- Large integer (spacing-100, spacing-200, spacing-350, etc.)
- Mix? (check Tailwind for example)
- Something else?

#External references
| System | Naming | Notes|
|:----|:----|:----|
|[Tailwind](https://tailwindcss.com/docs/customizing-spacing#default-spacing-scale)| Mixed ("px", integer, decimal) | Not really a brand specific design system. You will notice a much larger scale provided. | 
[Carbon Design System - Spacing](https://carbondesignsystem.com/guidelines/spacing/overview/#spacing-scale)
[Lightning Design System - Spacing](https://www.lightningdesignsystem.com/design-tokens/#category-spacing)
https://shoelace.style/tokens/spacing
spectrum size tokens
[spectrum spacing beta spacing tokens](https://github.com/adobe/spectrum-tokens/blob/210f646fce32f7e8485bd9c4682d5b8e8836c697/src/layout.json)

## 📋 Tasks
- [x] #718 
- [ ] Identify existing uses for context specific tokens
- [ ] Implement token set
- [ ] Update existing uses

**Comment by fredvisser** [comment]
Closing in favor of https://github.com/ni/nimble/issues/2089
